function MainApplication()
% MAINAPPLICATION MBUT desktop application entry point.
%
% Creates the MATLAB R2016b-compatible application shell, navigation,
% shared status bar, and all MBUT UI views.
%
% UI layer only. Backend integration is intentionally separated.

    clc;

    applicationRoot = fileparts(mfilename('fullpath'));
    addpath(applicationRoot);
    addpath(fullfile(applicationRoot, 'backend'));

    C.AppBackground    = [0.945 0.953 0.965];
    C.Sidebar          = [0.105 0.125 0.160];
    C.SidebarSelected  = [0.125 0.350 0.620];
    C.Header           = [1.000 1.000 1.000];
    C.ContentBackground = [0.945 0.953 0.965];

    C.TextPrimary      = [0.110 0.125 0.150];
    C.TextSecondary    = [0.430 0.460 0.510];
    C.TextLight        = [0.900 0.920 0.950];

    C.StatusBar        = [1.000 1.000 1.000];
    C.StatusBorder     = [0.855 0.875 0.905];
    C.StatusReady      = [0.145 0.520 0.330];
    C.StatusWorking    = [0.125 0.350 0.620];
    C.StatusWarning    = [0.850 0.560 0.120];
    C.StatusError      = [0.720 0.220 0.220];

    sidebarWidth    = 250;
    headerHeight    = 72;
    statusBarHeight = 28;

    minimumWidth    = 900;
    minimumHeight   = 550;
    defaultWidth    = 1280;
    defaultHeight   = 760;

    navHeight = 48;
    navGap    = 6;

    screenSize = get(0, 'ScreenSize');

    windowWidth  = min(defaultWidth, screenSize(3) - 40);
    windowHeight = min(defaultHeight, screenSize(4) - 80);

    windowWidth  = max(windowWidth, minimumWidth);
    windowHeight = max(windowHeight, minimumHeight);

    windowX = round((screenSize(3) - windowWidth) / 2);
    windowY = round((screenSize(4) - windowHeight) / 2);

    windowX = max(windowX, 1);
    windowY = max(windowY, 1);

    hFig = figure( ...
        'Name', 'Model Based Testing Tool', ...
        'NumberTitle', 'off', ...
        'MenuBar', 'none', ...
        'ToolBar', 'none', ...
        'Color', C.AppBackground, ...
        'Units', 'pixels', ...
        'Position', [windowX windowY windowWidth windowHeight], ...
        'Resize', 'on', ...
        'CloseRequestFcn', @closeApplication);

    app = struct();

    app.Figure        = hFig;
    app.CurrentView   = 1;
    app.NavAxes       = zeros(1, 5);
    app.NavBackground = zeros(1, 5);
    app.NavText       = zeros(1, 5);
    app.ViewPanels    = zeros(1, 5);

    app.Sidebar = uipanel( ...
        'Parent', hFig, ...
        'Units', 'pixels', ...
        'Position', [1 1 sidebarWidth windowHeight], ...
        'BackgroundColor', C.Sidebar, ...
        'BorderType', 'none');

    app.Header = uipanel( ...
        'Parent', hFig, ...
        'Units', 'pixels', ...
        'Position', ...
        [sidebarWidth + 1, ...
         windowHeight - headerHeight + 1, ...
         windowWidth - sidebarWidth, ...
         headerHeight], ...
        'BackgroundColor', C.Header, ...
        'BorderType', 'none');

    app.Content = uipanel( ...
        'Parent', hFig, ...
        'Units', 'pixels', ...
        'Position', ...
        [sidebarWidth + 1, ...
         statusBarHeight + 1, ...
         windowWidth - sidebarWidth, ...
         windowHeight - headerHeight - statusBarHeight], ...
        'BackgroundColor', C.ContentBackground, ...
        'BorderType', 'none');

    app.StatusBar = uipanel( ...
        'Parent', hFig, ...
        'Units', 'pixels', ...
        'Position', ...
        [sidebarWidth + 1, ...
         1, ...
         windowWidth - sidebarWidth, ...
         statusBarHeight], ...
        'BackgroundColor', C.StatusBar, ...
        'BorderType', 'line', ...
        'HighlightColor', C.StatusBorder, ...
        'ShadowColor', C.StatusBorder);

    app.StatusIndicator = uicontrol( ...
        'Parent', app.StatusBar, ...
        'Style', 'text', ...
        'Units', 'pixels', ...
        'Position', [14 4 14 18], ...
        'String', char(9679), ...
        'HorizontalAlignment', 'center', ...
        'FontName', 'Segoe UI Symbol', ...
        'FontSize', 9, ...
        'ForegroundColor', C.StatusReady, ...
        'BackgroundColor', C.StatusBar);

    app.StatusText = uicontrol( ...
        'Parent', app.StatusBar, ...
        'Style', 'text', ...
        'Units', 'pixels', ...
        'Position', [32 4 600 18], ...
        'String', 'Ready', ...
        'HorizontalAlignment', 'left', ...
        'FontName', 'Segoe UI', ...
        'FontSize', 8.5, ...
        'ForegroundColor', C.TextSecondary, ...
        'BackgroundColor', C.StatusBar);

    app.StatusRightText = uicontrol( ...
        'Parent', app.StatusBar, ...
        'Style', 'text', ...
        'Units', 'pixels', ...
        'Position', ...
        [windowWidth - sidebarWidth - 190, ...
         4, ...
         170, ...
         18], ...
        'String', 'MBUT', ...
        'HorizontalAlignment', 'right', ...
        'FontName', 'Segoe UI', ...
        'FontSize', 8, ...
        'ForegroundColor', C.TextSecondary, ...
        'BackgroundColor', C.StatusBar);

    app.BrandTitle = uicontrol( ...
        'Parent', app.Sidebar, ...
        'Style', 'text', ...
        'Units', 'pixels', ...
        'Position', [24 windowHeight - 57 205 28], ...
        'String', 'MBUT', ...
        'HorizontalAlignment', 'left', ...
        'FontName', 'Segoe UI', ...
        'FontSize', 15, ...
        'FontWeight', 'bold', ...
        'ForegroundColor', [1 1 1], ...
        'BackgroundColor', C.Sidebar);

    app.BrandSubtitle = uicontrol( ...
        'Parent', app.Sidebar, ...
        'Style', 'text', ...
        'Units', 'pixels', ...
        'Position', [24 windowHeight - 80 205 20], ...
        'String', 'SWE4 Unit Testing', ...
        'HorizontalAlignment', 'left', ...
        'FontName', 'Segoe UI', ...
        'FontSize', 9, ...
        'ForegroundColor', [0.570 0.620 0.700], ...
        'BackgroundColor', C.Sidebar);

    navItems = { ...
        'Model Setup', ...
        'Test Case Management', ...
        'Test Case Generation', ...
        'Batch Run', ...
        'Plot and Report'};

    navTop = windowHeight - 135;

    for i = 1:5

        yPosition = navTop - ((i - 1) * (navHeight + navGap));

        app.NavAxes(i) = axes( ...
            'Parent', app.Sidebar, ...
            'Units', 'pixels', ...
            'Position', [12 yPosition 226 navHeight], ...
            'XLim', [0 1], ...
            'YLim', [0 1], ...
            'Visible', 'off', ...
            'Color', 'none');

        app.NavBackground(i) = rectangle( ...
            'Parent', app.NavAxes(i), ...
            'Position', [0.01 0.05 0.98 0.90], ...
            'Curvature', [0.05 0.05], ...
            'FaceColor', C.Sidebar, ...
            'EdgeColor', C.Sidebar, ...
            'LineWidth', 1, ...
            'ButtonDownFcn', {@navigateToView, i});

        app.NavText(i) = text( ...
            0.08, ...
            0.50, ...
            navItems{i}, ...
            'Parent', app.NavAxes(i), ...
            'Units', 'normalized', ...
            'HorizontalAlignment', 'left', ...
            'VerticalAlignment', 'middle', ...
            'FontName', 'Segoe UI', ...
            'FontSize', 10, ...
            'FontWeight', 'normal', ...
            'Color', C.TextLight, ...
            'Interpreter', 'none', ...
            'ButtonDownFcn', {@navigateToView, i});

    end

    app.SidebarFooter = uicontrol( ...
        'Parent', app.Sidebar, ...
        'Style', 'text', ...
        'Units', 'pixels', ...
        'Position', [24 20 205 40], ...
        'String', sprintf('MATLAB R2016b\nDesktop Application'), ...
        'HorizontalAlignment', 'left', ...
        'FontName', 'Segoe UI', ...
        'FontSize', 8, ...
        'ForegroundColor', [0.480 0.530 0.610], ...
        'BackgroundColor', C.Sidebar);

    app.HeaderTitle = uicontrol( ...
        'Parent', app.Header, ...
        'Style', 'text', ...
        'Units', 'pixels', ...
        'Position', [30 33 600 27], ...
        'String', 'Model Setup', ...
        'HorizontalAlignment', 'left', ...
        'FontName', 'Segoe UI', ...
        'FontSize', 17, ...
        'FontWeight', 'bold', ...
        'ForegroundColor', C.TextPrimary, ...
        'BackgroundColor', C.Header);

    app.HeaderSubtitle = uicontrol( ...
        'Parent', app.Header, ...
        'Style', 'text', ...
        'Units', 'pixels', ...
        'Position', [31 10 700 20], ...
        'String', 'Configure and prepare the model workspace', ...
        'HorizontalAlignment', 'left', ...
        'FontName', 'Segoe UI', ...
        'FontSize', 9, ...
        'ForegroundColor', C.TextSecondary, ...
        'BackgroundColor', C.Header);

    for i = 1:5

        app.ViewPanels(i) = uipanel( ...
            'Parent', app.Content, ...
            'Units', 'normalized', ...
            'Position', [0 0 1 1], ...
            'BackgroundColor', C.ContentBackground, ...
            'BorderType', 'none', ...
            'Visible', 'off');

    end

    app.ModelSetupView = view_ModelSetup(app.ViewPanels(1));

    app.TestCaseManagementView = view_TestCaseManagement(app.ViewPanels(2));

    app.TestCaseGenerationView = view_TestCaseGeneration(app.ViewPanels(3));

    app.BatchRunView = view_BatchRun(app.ViewPanels(4));

    app.PlotAndReportView = view_PlotAndReport(app.ViewPanels(5));

    guidata(hFig, app);

    setappdata(hFig, 'rightPanel', app.Content);
    setappdata(hFig, 'statusText', app.StatusText);
    setappdata(hFig, 'statusIndicator', app.StatusIndicator);
    setappdata(hFig, 'templatesDir', fullfile(applicationRoot, 'report_templates'));

    setappdata(hFig, 'mainModelPathBox', app.ModelSetupView.MainModelEdit);
    setappdata(hFig, 'submoduleBox', app.ModelSetupView.SubmoduleEdit);
    setappdata(hFig, 'savePathBox', app.ModelSetupView.SavePathEdit);

    setappdata(hFig, 'mtcdXlsBox', app.TestCaseManagementView.TestCaseFileEdit);
    setappdata(hFig, 'stepTimeBox', app.TestCaseManagementView.SampleTimeEdit);
    setappdata(hFig, 'testSeqList', app.TestCaseManagementView.AvailableList);
    setappdata(hFig, 'selectedTestSeqList', app.TestCaseManagementView.SelectedList);
    setappdata(hFig, 'milChk', app.TestCaseManagementView.MILCheckbox);
    setappdata(hFig, 'silChk', app.TestCaseManagementView.SILCheckbox);
    setappdata(hFig, 'codeCoverageType', app.TestCaseManagementView.CoveragePopup);

    setappdata(hFig, 'excelPathListBox', app.BatchRunView.ExcelPathListBox);
    setappdata(hFig, 'excelPathList', {});
    setappdata(hFig, 'selectedExcelIdx', []);

    setappdata(hFig, 'sim_ddFolders', app.PlotAndReportView.FolderDropdown);
    setappdata(hFig, 'sim_ddSignals', app.PlotAndReportView.SignalDropdown);
    setappdata(hFig, 'sim_ddCompare', app.PlotAndReportView.CompareDropdown);
    setappdata(hFig, 'targetCoverageBox', app.PlotAndReportView.TargetCoverageEdit);
    setappdata(hFig, 'coverageTypeDropdown', app.PlotAndReportView.CoverageTypeDropdown);

    setappdata(hFig, 'mainModelPath', '');
    setappdata(hFig, 'submodulePath', '');
    setappdata(hFig, 'savePath', '');
    setappdata(hFig, 'mtcdXlsPath', '');
    setappdata(hFig, 'testCaseNames', {});
    setappdata(hFig, 'testCaseIDs', {});
    setappdata(hFig, 'testCaseMap', containers.Map);
    setappdata(hFig, 'slxFlag', false);
    setappdata(hFig, 'slxFilePath', '');
    setappdata(hFig, 'code_coverage_type', 1);

    set(hFig, ...
        'ResizeFcn', @resizeApplication);

    navigateToView([], [], 1);

    setStatus('Ready', 'ready');


    function navigateToView(~, ~, viewIndex)

        appData = guidata(hFig);

        viewTitles = { ...
            'Model Setup', ...
            'Test Case Management', ...
            'Test Case Generation', ...
            'Batch Run', ...
            'Plot and Report'};

        viewSubtitles = { ...
            'Configure and prepare the model workspace', ...
            'Load, inspect and manage test case data', ...
            'Generate test scenarios and test cases', ...
            'Execute multiple test configurations', ...
            'Analyse results and generate reports'};

        for k = 1:5

            set(appData.ViewPanels(k), ...
                'Visible', 'off');

            set(appData.NavBackground(k), ...
                'FaceColor', C.Sidebar, ...
                'EdgeColor', C.Sidebar);

            set(appData.NavText(k), ...
                'Color', C.TextLight, ...
                'FontWeight', 'normal');

        end

        set(appData.ViewPanels(viewIndex), ...
            'Visible', 'on');

        set(appData.NavBackground(viewIndex), ...
            'FaceColor', C.SidebarSelected, ...
            'EdgeColor', C.SidebarSelected);

        set(appData.NavText(viewIndex), ...
            'Color', [1 1 1], ...
            'FontWeight', 'bold');

        set(appData.HeaderTitle, ...
            'String', viewTitles{viewIndex});

        set(appData.HeaderSubtitle, ...
            'String', viewSubtitles{viewIndex});

        appData.CurrentView = viewIndex;

        guidata(hFig, appData);

        if viewIndex == 5
            ut_callbacks('refreshPlotFolders', hFig);
        end

    end


    function resizeApplication(~, ~)

        appData = guidata(hFig);

        if isempty(appData)
            return;
        end

        figPosition = get(hFig, 'Position');

        figWidth  = figPosition(3);
        figHeight = figPosition(4);

        newWidth  = max(figWidth, minimumWidth);
        newHeight = max(figHeight, minimumHeight);

        if newWidth ~= figWidth || newHeight ~= figHeight

            set(hFig, ...
                'Position', ...
                [figPosition(1) ...
                 figPosition(2) ...
                 newWidth ...
                 newHeight]);

            figWidth  = newWidth;
            figHeight = newHeight;

        end

        set(appData.Sidebar, ...
            'Position', ...
            [1 1 sidebarWidth figHeight]);

        set(appData.Header, ...
            'Position', ...
            [sidebarWidth + 1, ...
             figHeight - headerHeight + 1, ...
             figWidth - sidebarWidth, ...
             headerHeight]);

        set(appData.Content, ...
            'Position', ...
            [sidebarWidth + 1, ...
             statusBarHeight + 1, ...
             figWidth - sidebarWidth, ...
             figHeight - headerHeight - statusBarHeight]);

        set(appData.StatusBar, ...
            'Position', ...
            [sidebarWidth + 1, ...
             1, ...
             figWidth - sidebarWidth, ...
             statusBarHeight]);

        set(appData.StatusRightText, ...
            'Position', ...
            [figWidth - sidebarWidth - 190, ...
             4, ...
             170, ...
             18]);

        set(appData.BrandTitle, ...
            'Position', ...
            [24 figHeight - 57 205 28]);

        set(appData.BrandSubtitle, ...
            'Position', ...
            [24 figHeight - 80 205 20]);

        currentNavTop = figHeight - 135;

        for k = 1:5

            yPosition = ...
                currentNavTop - ...
                ((k - 1) * (navHeight + navGap));

            set(appData.NavAxes(k), ...
                'Position', ...
                [12 yPosition 226 navHeight]);

        end

        set(appData.SidebarFooter, ...
            'Position', ...
            [24 20 205 40]);

    end


    function setStatus(statusMessage, statusType)

        appData = guidata(hFig);

        if isempty(appData)
            return;
        end

        if nargin < 2
            statusType = 'ready';
        end

        switch lower(statusType)

            case 'working'
                indicatorColor = C.StatusWorking;

            case 'success'
                indicatorColor = C.StatusReady;

            case 'warning'
                indicatorColor = C.StatusWarning;

            case 'error'
                indicatorColor = C.StatusError;

            otherwise
                indicatorColor = C.StatusReady;

        end

        set(appData.StatusText, ...
            'String', statusMessage);

        set(appData.StatusIndicator, ...
            'ForegroundColor', indicatorColor);

        drawnow;

    end


    function closeApplication(~, ~)

        if ishandle(hFig)
            delete(hFig);
        end

    end

end
