function varargout = ut_callbacks(action, fig, varargin)

    if nargin < 2 || isempty(fig) || ~ishandle(fig)
        error( ...
            'ut_callbacks:InvalidFigure', ...
            'A valid application figure handle is required.');
    end

    if nargin < 1 || isempty(action)
        error( ...
            'ut_callbacks:InvalidAction', ...
            'A callback action is required.');
    end

    switch action

        case 'browseMainModel'
            browseMainModel(fig);

        case 'browseSubmodule'
            browseSubmodule(fig);

        case 'browseSavePath'
            browseSavePath(fig);

        case 'saveModelInfo'
            saveModelInformation(fig);

        case 'generateTestFrame'
            generateTestFrame(fig);

        case 'openTestFrame'
            openTestFrame(fig);

        case 'browseTestCaseFile'
            browseTestCaseFile(fig);

        case 'loadTestCases'
            loadTestCases(fig);

        case 'availableDoubleClick'
            availableTestCaseDoubleClick(fig);

        case 'selectAllTestCases'
            selectAllTestCases(fig);

        case 'deleteSelectedTestCases'
            deleteSelectedTestCases(fig);

        case 'executeSimulation'
            executeSimulation(fig);

        case 'generateCode'
            generateCode(fig);

        case 'runTestCaseGenerator'
            runTestCaseGenerator(fig);

        case 'addBatchFile'
            addBatchFile(fig);

        case 'batchSelectionChanged'
            batchSelectionChanged(fig);

        case 'deleteBatchFile'
            deleteBatchFile(fig);

        case 'executeBatch'
            executeBatch(fig);

        case 'automaticBatchRun'
            automaticBatchRun(fig);

        case 'runBatchTestCases'
            runBatchTestCases(fig);

        case 'refreshPlotFolders'
            refreshPlotFolders(fig);

        case 'plotFolderChanged'
            refreshSignals(fig);

        case 'plotSignal'
            plotSignal(fig);

        case 'generateReport'
            generateReport(fig);

        otherwise
            error( ...
                'ut_callbacks:UnknownAction', ...
                'Unknown callback action: %s', ...
                action);

    end

    if nargout > 0
        varargout{1} = [];
    end

end


function browseMainModel(fig)

    [fileName, folderPath] = uigetfile( ...
        {'*.slx;*.mdl', 'Simulink Models (*.slx, *.mdl)'}, ...
        'Select Main Model');

    if isequal(fileName, 0)
        return;
    end

    modelPath = fullfile(folderPath, fileName);

    ut_setState(fig, 'mainModelPath', modelPath);

    setApplicationControl( ...
        fig, ...
        'mainModelPathBox', ...
        'String', ...
        modelPath);

    ut_setStatus( ...
        fig, ...
        'Main model selected.', ...
        'success');

end


function browseSubmodule(fig)

    mainModelPath = getappdata(fig, 'mainModelPath');

    if isempty(mainModelPath) || ...
            exist(mainModelPath, 'file') ~= 2

        errordlg( ...
            'Select a valid Main Model first.', ...
            'Model Setup');

        return;

    end

    ut_setStatus( ...
        fig, ...
        'Loading model hierarchy...', ...
        'working');

    drawnow;

    try

        [~, modelName] = fileparts(mainModelPath);

        load_system(mainModelPath);

        subsystemPaths = find_system( ...
            modelName, ...
            'SearchDepth', 2, ...
            'BlockType', 'SubSystem');

        subsystemPaths = subsystemPaths( ...
            ~strcmp(subsystemPaths, modelName));

        if isempty(subsystemPaths)

            ut_setStatus( ...
                fig, ...
                'No submodules found.', ...
                'error');

            errordlg( ...
                'No submodules were found in the selected model.', ...
                'Model Setup');

            return;

        end

        [selectedIndex, selectionMade] = listdlg( ...
            'PromptString', 'Select Submodule', ...
            'SelectionMode', 'single', ...
            'ListString', subsystemPaths, ...
            'ListSize', [500 350]);

        if ~selectionMade

            ut_setStatus( ...
                fig, ...
                'Submodule selection cancelled.', ...
                'ready');

            return;

        end

        selectedSubsystem = subsystemPaths{selectedIndex};

        ut_setState( ...
            fig, ...
            'submodulePath', ...
            selectedSubsystem);

        setApplicationControl( ...
            fig, ...
            'submoduleBox', ...
            'String', ...
            selectedSubsystem);

        ut_setStatus( ...
            fig, ...
            'Submodule selected.', ...
            'success');

    catch ME

        ut_setStatus( ...
            fig, ...
            'Unable to load submodules.', ...
            'error');

        errordlg( ...
            ME.message, ...
            'Submodule Error');

    end

end


function browseSavePath(fig)

    folderPath = uigetdir( ...
        pwd, ...
        'Select Save Location');

    if isequal(folderPath, 0)
        return;
    end

    ut_setState( ...
        fig, ...
        'savePath', ...
        folderPath);

    setApplicationControl( ...
        fig, ...
        'savePathBox', ...
        'String', ...
        folderPath);

    ut_setStatus( ...
        fig, ...
        'Save path selected.', ...
        'success');

end


function saveModelInformation(fig)

    mainModelPath = getControlString( ...
        fig, ...
        'mainModelPathBox');

    submodulePath = getControlString( ...
        fig, ...
        'submoduleBox');

    savePath = getControlString( ...
        fig, ...
        'savePathBox');

    if isempty(mainModelPath) || ...
            isempty(submodulePath) || ...
            isempty(savePath)

        errordlg( ...
            ['Main Model, Submodule, and Save Path are ' ...
             'mandatory.'], ...
            'Model Setup');

        return;

    end

    if exist(mainModelPath, 'file') ~= 2

        errordlg( ...
            'The selected Main Model does not exist.', ...
            'Model Setup');

        return;

    end

    if exist(savePath, 'dir') ~= 7

        errordlg( ...
            'The selected Save Path does not exist.', ...
            'Model Setup');

        return;

    end

    ut_setState( ...
        fig, ...
        'mainModelPath', ...
        mainModelPath);

    ut_setState( ...
        fig, ...
        'submodulePath', ...
        submodulePath);

    ut_setState( ...
        fig, ...
        'savePath', ...
        savePath);

    ut_setStatus( ...
        fig, ...
        'Model configuration saved.', ...
        'success');

    msgbox( ...
        'Model configuration saved successfully.', ...
        'Model Setup');

end


function generateTestFrame(fig)

    mainModelPath = getappdata( ...
        fig, ...
        'mainModelPath');

    submodulePath = getappdata( ...
        fig, ...
        'submodulePath');

    savePath = getappdata( ...
        fig, ...
        'savePath');

    if isempty(mainModelPath) || ...
            isempty(submodulePath) || ...
            isempty(savePath)

        errordlg( ...
            'Save the model configuration first.', ...
            'Generate Test Frame');

        return;

    end

    [~, mainModelName] = fileparts(mainModelPath);

    ut_setStatus( ...
        fig, ...
        'Generating test frame...', ...
        'working');

    drawnow;

    try

        [frameCreated, testFramePath] = Frame_Creation1( ...
            mainModelName, ...
            submodulePath, ...
            savePath);

        ut_setState( ...
            fig, ...
            'slxFlag', ...
            frameCreated);

        ut_setState( ...
            fig, ...
            'slxFilePath', ...
            testFramePath);

        if frameCreated

            ut_setStatus( ...
                fig, ...
                'Test frame generated successfully.', ...
                'success');

            msgbox( ...
                'Frame generation completed.', ...
                'Generate Test Frame');

        else

            ut_setStatus( ...
                fig, ...
                'Test frame generation failed.', ...
                'error');

            errordlg( ...
                'The backend did not confirm frame generation.', ...
                'Generate Test Frame');

        end

    catch ME

        ut_setStatus( ...
            fig, ...
            'Test frame generation failed.', ...
            'error');

        errordlg( ...
            ME.message, ...
            'Generate Test Frame');

    end

end


function openTestFrame(fig)

    [fileName, folderPath] = uigetfile( ...
        {'*.slx', 'Simulink Model (*.slx)'}, ...
        'Select Test Frame');

    if isequal(fileName, 0)
        return;
    end

    testFramePath = fullfile( ...
        folderPath, ...
        fileName);

    ut_setStatus( ...
        fig, ...
        'Opening test frame...', ...
        'working');

    drawnow;

    try

        open_system(testFramePath);

        ut_setState( ...
            fig, ...
            'slxFlag', ...
            true);

        ut_setState( ...
            fig, ...
            'slxFilePath', ...
            testFramePath);

        ut_setStatus( ...
            fig, ...
            'Test frame opened.', ...
            'success');

    catch ME

        ut_setStatus( ...
            fig, ...
            'Unable to open test frame.', ...
            'error');

        errordlg( ...
            ME.message, ...
            'Open Test Frame');

    end

end


function browseTestCaseFile(fig)

    [fileName, folderPath] = uigetfile( ...
        {'*.xml', 'XML Test Case Files (*.xml)'}, ...
        'Select XML Test Case File');

    if isequal(fileName, 0)
        return;
    end

    xmlPath = fullfile( ...
        folderPath, ...
        fileName);

    ut_setStatus( ...
        fig, ...
        'Reading test case file...', ...
        'working');

    drawnow;

    try

        parseTestCases( ...
            fig, ...
            xmlPath);

        ut_setState( ...
            fig, ...
            'mtcdXlsPath', ...
            xmlPath);

        setApplicationControl( ...
            fig, ...
            'mtcdXlsBox', ...
            'String', ...
            xmlPath);

        ut_setStatus( ...
            fig, ...
            'Test case XML selected.', ...
            'success');

    catch ME

        ut_setStatus( ...
            fig, ...
            'Unable to read test case XML.', ...
            'error');

        errordlg( ...
            ME.message, ...
            'Test Case File');

    end

end


function parseTestCases(fig, xmlPath)

    xmlDocument = xmlread(xmlPath);

    testCaseNodes = xmlDocument.getElementsByTagName( ...
        'test-case');

    testCaseNames = {};
    testCaseIDs = {};
    testCaseMap = containers.Map;

    for nodeIndex = 0:testCaseNodes.getLength - 1

        testCaseNode = testCaseNodes.item(nodeIndex);

        testCaseID = strtrim(char( ...
            testCaseNode.getAttribute( ...
                'test-case-id')));

        testCaseName = strtrim(char( ...
            testCaseNode.getAttribute( ...
                'test-case-name')));

        if isempty(testCaseID) || ...
                isempty(testCaseName)

            continue;

        end

        testCaseNames{end + 1, 1} = testCaseName; %#ok<AGROW>
        testCaseIDs{end + 1, 1} = testCaseID; %#ok<AGROW>

        testCaseMap(testCaseName) = testCaseID;

    end

    if isempty(testCaseNames)

        error( ...
            'ut_callbacks:NoTestCases', ...
            'No valid test cases were found in the XML file.');

    end

    availableList = getApplicationControl( ...
        fig, ...
        'testSeqList');

    selectedList = getApplicationControl( ...
        fig, ...
        'selectedTestSeqList');

    set( ...
        availableList, ...
        'String', testCaseNames, ...
        'Value', [], ...
        'Min', 0, ...
        'Max', max(2, numel(testCaseNames)));

    set( ...
        selectedList, ...
        'String', {}, ...
        'Value', []);

    ut_setState( ...
        fig, ...
        'testCaseNames', ...
        testCaseNames);

    ut_setState( ...
        fig, ...
        'testCaseIDs', ...
        testCaseIDs);

    ut_setState( ...
        fig, ...
        'testCaseMap', ...
        testCaseMap);

end


function loadTestCases(fig)

    xmlPath = getControlString( ...
        fig, ...
        'mtcdXlsBox');

    sampleTime = str2double(getControlString( ...
        fig, ...
        'stepTimeBox'));

    if isempty(xmlPath) || ...
            exist(xmlPath, 'file') ~= 2

        errordlg( ...
            'Select a valid XML test case file.', ...
            'Test Case Management');

        return;

    end

    if isnan(sampleTime) || ...
            ~isfinite(sampleTime) || ...
            sampleTime <= 0

        errordlg( ...
            'Sample Time must be a positive numeric value.', ...
            'Test Case Management');

        return;

    end

    savePath = getappdata( ...
        fig, ...
        'savePath');

    submodulePath = getappdata( ...
        fig, ...
        'submodulePath');

    if isempty(savePath) || ...
            isempty(submodulePath)

        errordlg( ...
            'Complete Model Setup first.', ...
            'Test Case Management');

        return;

    end

    [~, submoduleName] = fileparts(submodulePath);

    testFolderPath = fullfile( ...
        savePath, ...
        ['Test_' submoduleName]);

    if exist(testFolderPath, 'dir') ~= 7
        mkdir(testFolderPath);
    end

    [~, xmlName, xmlExtension] = fileparts(xmlPath);

    targetXmlPath = fullfile( ...
        testFolderPath, ...
        [xmlName xmlExtension]);

    sourceFolder = fileparts(xmlPath);

    if ~strcmpi(sourceFolder, testFolderPath)

        copyfile( ...
            xmlPath, ...
            targetXmlPath);

        xmlPath = targetXmlPath;

    end

    dataFolders = dir(fullfile( ...
        fileparts(xmlPath), ...
        '*_data'));

    dataFolders = dataFolders([dataFolders.isdir]);

    if isempty(dataFolders)

        errordlg( ...
            'No *_data folder was found next to the XML file.', ...
            'Load Test Cases');

        return;

    end

    dataDirectory = fullfile( ...
        fileparts(xmlPath), ...
        dataFolders(1).name);

    ut_setState( ...
        fig, ...
        'mtcdXlsPath', ...
        xmlPath);

    setApplicationControl( ...
        fig, ...
        'mtcdXlsBox', ...
        'String', ...
        xmlPath);

    ut_setStatus( ...
        fig, ...
        'Loading test cases...', ...
        'working');

    drawnow;

    try

        build_from_xml( ...
            xmlPath, ...
            sampleTime, ...
            dataDirectory);

        matDirectory = fullfile( ...
            testFolderPath, ...
            'mat_file');

        if exist(matDirectory, 'dir') ~= 7
            mkdir(matDirectory);
        end

        matFiles = dir(fullfile( ...
            testFolderPath, ...
            '*.mat'));

        for fileIndex = 1:numel(matFiles)

            sourceMatPath = fullfile( ...
                testFolderPath, ...
                matFiles(fileIndex).name);

            targetMatPath = fullfile( ...
                matDirectory, ...
                matFiles(fileIndex).name);

            if exist(targetMatPath, 'file') == 2
                delete(targetMatPath);
            end

            movefile( ...
                sourceMatPath, ...
                targetMatPath);

        end

        parseTestCases( ...
            fig, ...
            xmlPath);

        ut_setStatus( ...
            fig, ...
            'Test cases loaded successfully.', ...
            'success');

        msgbox( ...
            'Test cases loaded successfully.', ...
            'Load Test Cases');

    catch ME

        ut_setStatus( ...
            fig, ...
            'Unable to load test cases.', ...
            'error');

        errordlg( ...
            ME.message, ...
            'Load Test Cases');

    end

end


function availableTestCaseDoubleClick(fig)

    if strcmp(get(fig, 'SelectionType'), 'open')
        addSelectedCases(fig);
    end

end


function addSelectedCases(fig)

    availableList = getApplicationControl( ...
        fig, ...
        'testSeqList');

    selectedList = getApplicationControl( ...
        fig, ...
        'selectedTestSeqList');

    availableItems = normalizeListboxStrings( ...
        get(availableList, 'String'));

    selectedIndices = get( ...
        availableList, ...
        'Value');

    if isempty(availableItems) || ...
            isempty(selectedIndices)

        return;

    end

    selectedItems = normalizeListboxStrings( ...
        get(selectedList, 'String'));

    for index = 1:numel(selectedIndices)

        itemIndex = selectedIndices(index);

        if itemIndex > numel(availableItems)
            continue;
        end

        itemName = availableItems{itemIndex};

        if ~any(strcmp(selectedItems, itemName))
            selectedItems{end + 1, 1} = itemName; %#ok<AGROW>
        end

    end

    set( ...
        selectedList, ...
        'String', selectedItems, ...
        'Value', []);

    ut_setStatus( ...
        fig, ...
        'Test case selection updated.', ...
        'success');

end


function selectAllTestCases(fig)

    availableList = getApplicationControl( ...
        fig, ...
        'testSeqList');

    selectedList = getApplicationControl( ...
        fig, ...
        'selectedTestSeqList');

    availableItems = normalizeListboxStrings( ...
        get(availableList, 'String'));

    set( ...
        selectedList, ...
        'String', availableItems, ...
        'Value', []);

    ut_setStatus( ...
        fig, ...
        'All test cases selected.', ...
        'success');

end


function deleteSelectedTestCases(fig)

    selectedList = getApplicationControl( ...
        fig, ...
        'selectedTestSeqList');

    selectedItems = normalizeListboxStrings( ...
        get(selectedList, 'String'));

    selectedIndices = get( ...
        selectedList, ...
        'Value');

    if isempty(selectedItems) || ...
            isempty(selectedIndices)

        return;

    end

    selectedIndices = selectedIndices( ...
        selectedIndices <= numel(selectedItems));

    selectedItems(selectedIndices) = [];

    set( ...
        selectedList, ...
        'String', selectedItems, ...
        'Value', []);

    ut_setStatus( ...
        fig, ...
        'Selected test cases removed.', ...
        'success');

end


function executeSimulation(fig)

    xmlPath = getappdata( ...
        fig, ...
        'mtcdXlsPath');

    selectedList = getApplicationControl( ...
        fig, ...
        'selectedTestSeqList');

    selectedTestCases = normalizeListboxStrings( ...
        get(selectedList, 'String'));

    testCaseMap = getappdata( ...
        fig, ...
        'testCaseMap');

    if isempty(xmlPath) || ...
            isempty(selectedTestCases)

        errordlg( ...
            ['Select a test case file and at least one ' ...
             'test case.'], ...
            'Execute Simulation');

        return;

    end

    if isempty(testCaseMap) || ...
            ~isa(testCaseMap, 'containers.Map')

        errordlg( ...
            ['Test case mapping is unavailable. ' ...
             'Reload the XML file.'], ...
            'Execute Simulation');

        return;

    end

    testCaseIDs = cell( ...
        numel(selectedTestCases), ...
        1);

    for testCaseIndex = 1:numel(selectedTestCases)

        testCaseName = selectedTestCases{testCaseIndex};

        if ~isKey(testCaseMap, testCaseName)

            errordlg( ...
                ['Unable to resolve Test Case ID for: ' ...
                 testCaseName], ...
                'Execute Simulation');

            return;

        end

        testCaseIDs{testCaseIndex} = ...
            testCaseMap(testCaseName);

    end

    milEnabled = logical(get( ...
        getApplicationControl(fig, 'milChk'), ...
        'Value'));

    silEnabled = logical(get( ...
        getApplicationControl(fig, 'silChk'), ...
        'Value'));

    if ~milEnabled && ~silEnabled

        errordlg( ...
            'Select MIL, SIL, or both.', ...
            'Execute Simulation');

        return;

    end

    coverageControl = getApplicationControl( ...
        fig, ...
        'codeCoverageType');

    coverageValue = get( ...
        coverageControl, ...
        'Value');

    ut_setState( ...
        fig, ...
        'code_coverage_type', ...
        coverageValue);

    ut_setState( ...
        fig, ...
        'TestseqID', ...
        testCaseIDs);

    [frameName, framePath] = resolveTestFrame( ...
        fig, ...
        xmlPath);

    if isempty(frameName)

        errordlg( ...
            'No test frame SLX file was found.', ...
            'Execute Simulation');

        return;

    end

    ut_setStatus( ...
        fig, ...
        'Executing simulation...', ...
        'working');

    drawnow;

    try

        if ~bdIsLoaded(frameName)
            load_system(framePath);
        end

        fcn_Simulate_frame( ...
            xmlPath, ...
            testCaseIDs, ...
            milEnabled, ...
            silEnabled, ...
            frameName);

        ut_setStatus( ...
            fig, ...
            'Simulation completed.', ...
            'success');

    catch ME

        ut_setStatus( ...
            fig, ...
            'Simulation failed.', ...
            'error');

        errordlg( ...
            ME.message, ...
            'Execute Simulation');

    end

end


function generateCode(fig)

    xmlPath = getappdata( ...
        fig, ...
        'mtcdXlsPath');

    if isempty(xmlPath)

        errordlg( ...
            'Select a test case file first.', ...
            'Generate Code');

        return;

    end

    [frameName, framePath] = resolveTestFrame( ...
        fig, ...
        xmlPath);

    if isempty(frameName)

        errordlg( ...
            'No test frame SLX file was found.', ...
            'Generate Code');

        return;

    end

    ut_setStatus( ...
        fig, ...
        'Generating code...', ...
        'working');

    drawnow;

    try

        if ~bdIsLoaded(frameName)
            load_system(framePath);
        end

        generationSucceeded = ut_generateCode( ...
            fig, ...
            frameName);

        if generationSucceeded

            ut_setStatus( ...
                fig, ...
                'Code generation completed.', ...
                'success');

            msgbox( ...
                'Code generation successful.', ...
                'Generate Code');

        else

            ut_setStatus( ...
                fig, ...
                'Code generation failed.', ...
                'error');

            errordlg( ...
                'Code generation failed. Check the build logs.', ...
                'Generate Code');

        end

    catch ME

        ut_setStatus( ...
            fig, ...
            'Code generation failed.', ...
            'error');

        errordlg( ...
            ME.message, ...
            'Generate Code');

    end

end


function runTestCaseGenerator(fig)

    applicationRoot = fileparts( ...
        mfilename('fullpath'));

    executablePath = fullfile( ...
        applicationRoot, ...
        'TestCase.exe');

    if exist(executablePath, 'file') ~= 2

        errordlg( ...
            sprintf( ...
                'TestCase.exe was not found:\n%s', ...
                executablePath), ...
            'Test Case Generation');

        return;

    end

    ut_setStatus( ...
        fig, ...
        'Running test case generator...', ...
        'working');

    drawnow;

    try

        command = sprintf( ...
            '"%s"', ...
            executablePath);

        [exitStatus, commandOutput] = system(command);

        if exitStatus ~= 0

            error( ...
                'ut_callbacks:GeneratorFailed', ...
                '%s', ...
                commandOutput);

        end

        ut_setStatus( ...
            fig, ...
            'Test case generation completed.', ...
            'success');

    catch ME

        ut_setStatus( ...
            fig, ...
            'Test case generation failed.', ...
            'error');

        errordlg( ...
            ME.message, ...
            'Test Case Generation');

    end

end


function addBatchFile(fig)

    [fileName, folderPath] = uigetfile( ...
        {'*.xml', 'XML Test Case Files (*.xml)'}, ...
        'Add Test Case File');

    if isequal(fileName, 0)
        return;
    end

    batchPaths = getappdata( ...
        fig, ...
        'excelPathList');

    if isempty(batchPaths)
        batchPaths = {};
    end

    selectedPath = fullfile( ...
        folderPath, ...
        fileName);

    if ~any(strcmp(batchPaths, selectedPath))
        batchPaths{end + 1, 1} = selectedPath;
    end

    updateBatchPathList( ...
        fig, ...
        batchPaths);

    ut_setStatus( ...
        fig, ...
        'Batch file added.', ...
        'success');

end


function batchSelectionChanged(fig)

    batchList = getApplicationControl( ...
        fig, ...
        'excelPathListBox');

    setappdata( ...
        fig, ...
        'selectedExcelIdx', ...
        get(batchList, 'Value'));

end


function deleteBatchFile(fig)

    batchPaths = getappdata( ...
        fig, ...
        'excelPathList');

    selectedIndices = getappdata( ...
        fig, ...
        'selectedExcelIdx');

    if isempty(batchPaths) || ...
            isempty(selectedIndices)

        return;

    end

    selectedIndices = selectedIndices( ...
        selectedIndices <= numel(batchPaths));

    batchPaths(selectedIndices) = [];

    setappdata( ...
        fig, ...
        'selectedExcelIdx', ...
        []);

    updateBatchPathList( ...
        fig, ...
        batchPaths);

    ut_setStatus( ...
        fig, ...
        'Batch file removed.', ...
        'success');

end


function executeBatch(fig)

    batchPaths = getappdata( ...
        fig, ...
        'excelPathList');

    if isempty(batchPaths)

        errordlg( ...
            'Add at least one test case file.', ...
            'Batch Run');

        return;

    end

    ut_setStatus( ...
        fig, ...
        'Executing batch simulation...', ...
        'working');

    drawnow;

    try

        batch_run(batchPaths);

        ut_setStatus( ...
            fig, ...
            'Batch simulation completed.', ...
            'success');

    catch ME

        ut_setStatus( ...
            fig, ...
            'Batch simulation failed.', ...
            'error');

        errordlg( ...
            ME.message, ...
            'Batch Run');

    end

end


function automaticBatchRun(fig)

    rootFolder = uigetdir( ...
        pwd, ...
        'Select Root Folder for Batch Run');

    if isequal(rootFolder, 0)
        return;
    end

    userChoice = questdlg( ...
        sprintf( ...
            ['Selected folder:\n\n%s\n\n' ...
             'Choose the batch operation.'], ...
            rootFolder), ...
        'Confirm Batch Run', ...
        'Continue with Batch Run', ...
        'Generate only Reports', ...
        'Cancel', ...
        'Continue with Batch Run');

    if isempty(userChoice) || ...
            strcmp(userChoice, 'Cancel')

        ut_setStatus( ...
            fig, ...
            'Batch run cancelled.', ...
            'ready');

        return;

    end

    ut_setStatus( ...
        fig, ...
        'Scanning batch folders...', ...
        'working');

    drawnow;

    batchPaths = findBatchXmlFiles(rootFolder);

    if isempty(batchPaths)

        ut_setStatus( ...
            fig, ...
            'No batch XML files found.', ...
            'error');

        errordlg( ...
            ['No Test_* folders containing *_TestCase.xml ' ...
             'files were found.'], ...
            'Batch Run');

        return;

    end

    updateBatchPathList( ...
        fig, ...
        batchPaths);

    if strcmp(userChoice, 'Generate only Reports')

        generateReportForPaths( ...
            fig, ...
            batchPaths);

    else

        executeBatch(fig);

    end

end


function runBatchTestCases(fig)

    testCaseFolder = uigetdir( ...
        pwd, ...
        'Select Folder Containing XML Test Cases');

    if isequal(testCaseFolder, 0)
        return;
    end

    xmlFiles = dir(fullfile( ...
        testCaseFolder, ...
        '*.xml'));

    if isempty(xmlFiles)

        errordlg( ...
            'No XML files were found.', ...
            'Test Cases Run');

        return;

    end

    batchPaths = cell( ...
        numel(xmlFiles), ...
        1);

    for fileIndex = 1:numel(xmlFiles)

        batchPaths{fileIndex} = fullfile( ...
            testCaseFolder, ...
            xmlFiles(fileIndex).name);

    end

    updateBatchPathList( ...
        fig, ...
        batchPaths);

    ut_setStatus( ...
        fig, ...
        'Executing test case batch...', ...
        'working');

    drawnow;

    try

        perform_full_testcases_batch_run( ...
            xmlFiles, ...
            fig);

        ut_setStatus( ...
            fig, ...
            sprintf( ...
                'Executed %d test case files.', ...
                numel(xmlFiles)), ...
            'success');

    catch ME

        ut_setStatus( ...
            fig, ...
            'Test case batch execution failed.', ...
            'error');

        errordlg( ...
            ME.message, ...
            'Test Cases Run');

    end

end


function batchPaths = findBatchXmlFiles(rootFolder)

    batchPaths = {};

    folderPaths = strsplit( ...
        genpath(rootFolder), ...
        pathsep);

    folderPaths = folderPaths( ...
        ~cellfun('isempty', folderPaths));

    for folderIndex = 1:numel(folderPaths)

        currentFolder = folderPaths{folderIndex};

        [~, folderName] = fileparts(currentFolder);

        if ~strncmp(folderName, 'Test_', 5)
            continue;
        end

        xmlFiles = dir(fullfile( ...
            currentFolder, ...
            '*_TestCase.xml'));

        for fileIndex = 1:numel(xmlFiles)

            batchPaths{end + 1, 1} = fullfile( ... %#ok<AGROW>
                currentFolder, ...
                xmlFiles(fileIndex).name);

        end

    end

end


function updateBatchPathList(fig, batchPaths)

    if isempty(batchPaths)
        batchPaths = {};
    end

    ut_setState( ...
        fig, ...
        'excelPathList', ...
        batchPaths);

    batchList = getApplicationControl( ...
        fig, ...
        'excelPathListBox');

    if isempty(batchPaths)

        set( ...
            batchList, ...
            'String', {}, ...
            'Value', []);

    else

        set( ...
            batchList, ...
            'String', batchPaths, ...
            'Value', 1);

    end

    updateBatchCount(fig);

end


function refreshPlotFolders(fig)

    folderDropdown = getApplicationControl( ...
        fig, ...
        'sim_ddFolders');

    xmlPath = getappdata( ...
        fig, ...
        'mtcdXlsPath');

    if isempty(xmlPath) || ...
            exist(xmlPath, 'file') ~= 2

        set( ...
            folderDropdown, ...
            'String', {'<No Test Case Path>'}, ...
            'Value', 1);

        setApplicationControl( ...
            fig, ...
            'sim_ddSignals', ...
            'String', ...
            {'<No signals>'}, ...
            'Value', ...
            1);

        return;

    end

    baseFolder = fileparts(xmlPath);

    testSequenceFolders = dir(fullfile( ...
        baseFolder, ...
        'TS_*'));

    testSequenceFolders = testSequenceFolders( ...
        [testSequenceFolders.isdir]);

    if isempty(testSequenceFolders)
        folderNames = {'<No TS Folders>'};
    else
        folderNames = {testSequenceFolders.name};
    end

    set( ...
        folderDropdown, ...
        'String', folderNames, ...
        'Value', 1);

    refreshSignals(fig);

end


function refreshSignals(fig)

    signalDropdown = getApplicationControl( ...
        fig, ...
        'sim_ddSignals');

    xmlPath = getappdata( ...
        fig, ...
        'mtcdXlsPath');

    if isempty(xmlPath) || ...
            exist(xmlPath, 'file') ~= 2

        set( ...
            signalDropdown, ...
            'String', {'<No signals>'}, ...
            'Value', 1);

        return;

    end

    dataFolders = dir(fullfile( ...
        fileparts(xmlPath), ...
        '*_data'));

    dataFolders = dataFolders([dataFolders.isdir]);

    if isempty(dataFolders)

        set( ...
            signalDropdown, ...
            'String', {'<No Data Folder>'}, ...
            'Value', 1);

        return;

    end

    dataFolderPath = fullfile( ...
        fileparts(xmlPath), ...
        dataFolders(1).name);

    outputPortPath = fullfile( ...
        dataFolderPath, ...
        'outports.json');

    if exist(outputPortPath, 'file') ~= 2

        set( ...
            signalDropdown, ...
            'String', {'<No Outports File>'}, ...
            'Value', 1);

        return;

    end

    try

        outputPortData = readJsonFile(outputPortPath);

        signalNames = extractSignalNames( ...
            outputPortData);

        if isempty(signalNames)
            signalNames = {'<No signals>'};
        end

        set( ...
            signalDropdown, ...
            'String', signalNames, ...
            'Value', 1);

    catch

        set( ...
            signalDropdown, ...
            'String', {'<Invalid Outports File>'}, ...
            'Value', 1);

    end

end


function data = readJsonFile(filePath)

    fileIdentifier = fopen( ...
        filePath, ...
        'r');

    if fileIdentifier == -1

        error( ...
            'ut_callbacks:JsonReadError', ...
            'Unable to open JSON file: %s', ...
            filePath);

    end

    cleanupObject = onCleanup( ...
        @() fclose(fileIdentifier)); %#ok<NASGU>

    rawText = fread( ...
        fileIdentifier, ...
        '*char')';

    rawText = strtrim(rawText);

    if isempty(rawText)
        data = [];
        return;
    end

    data = jsondecode(rawText);

end


function signalNames = extractSignalNames(outputPortData)

    signalNames = {};

    if isempty(outputPortData)
        return;
    end

    if isstruct(outputPortData)

        for dataIndex = 1:numel(outputPortData)

            if isfield( ...
                    outputPortData(dataIndex), ...
                    'signal')

                signalName = strtrim( ...
                    outputPortData(dataIndex).signal);

                if ~isempty(signalName)

                    signalNames{end + 1, 1} = ...
                        signalName; %#ok<AGROW>

                end

            end

        end

    end

end


function plotSignal(fig)

    selectedFolder = getPopupValue( ...
        getApplicationControl(fig, 'sim_ddFolders'));

    selectedSignal = getPopupValue( ...
        getApplicationControl(fig, 'sim_ddSignals'));

    comparisonMode = getPopupValue( ...
        getApplicationControl(fig, 'sim_ddCompare'));

    if isPlaceholderValue(selectedFolder) || ...
            isPlaceholderValue(selectedSignal)

        errordlg( ...
            'Select a valid TS Folder and Signal.', ...
            'Plot Signal');

        return;

    end

    xmlPath = getappdata( ...
        fig, ...
        'mtcdXlsPath');

    if isempty(xmlPath)

        errordlg( ...
            'Load a test case file first.', ...
            'Plot Signal');

        return;

    end

    baseFolder = fileparts(xmlPath);

    milEnabled = 1;

    silEnabled = strcmp( ...
        comparisonMode, ...
        'MIL vs SIL');

    ut_setStatus( ...
        fig, ...
        'Plotting signal...', ...
        'working');

    drawnow;

    try

        plot_signal_from_mat( ...
            baseFolder, ...
            selectedFolder, ...
            selectedSignal, ...
            milEnabled, ...
            silEnabled);

        ut_setStatus( ...
            fig, ...
            'Signal plotted successfully.', ...
            'success');

    catch ME

        ut_setStatus( ...
            fig, ...
            'Signal plotting failed.', ...
            'error');

        errordlg( ...
            ME.message, ...
            'Plot Signal');

    end

end


function generateReport(fig)

    targetCoverage = str2double(getControlString( ...
        fig, ...
        'targetCoverageBox'));

    if isnan(targetCoverage) || ...
            ~isfinite(targetCoverage) || ...
            targetCoverage < 0 || ...
            targetCoverage > 100

        errordlg( ...
            'Target Coverage must be between 0 and 100.', ...
            'Generate Report');

        return;

    end

    coverageDropdown = getApplicationControl( ...
        fig, ...
        'coverageTypeDropdown');

    coverageType = getPopupValue(coverageDropdown);

    ut_setState( ...
        fig, ...
        'target_coverage', ...
        targetCoverage);

    ut_setState( ...
        fig, ...
        'coverage_type', ...
        coverageType);

    reportPaths = getappdata( ...
        fig, ...
        'excelPathList');

    if isempty(reportPaths)

        xmlPath = getappdata( ...
            fig, ...
            'mtcdXlsPath');

        if isempty(xmlPath)

            errordlg( ...
                'Load a test case file first.', ...
                'Generate Report');

            return;

        end

        reportPaths = {xmlPath};

    end

    generateReportForPaths( ...
        fig, ...
        reportPaths);

end


function generateReportForPaths(fig, reportPaths)

    templatesDirectory = getappdata( ...
        fig, ...
        'templatesDir');

    if isempty(templatesDirectory) || ...
            exist(templatesDirectory, 'dir') ~= 7

        errordlg( ...
            sprintf( ...
                'Report templates folder was not found:\n%s', ...
                templatesDirectory), ...
            'Generate Report');

        return;

    end

    ut_setStatus( ...
        fig, ...
        'Generating HTML report...', ...
        'working');

    drawnow;

    try

        indexPath = build_full_report( ...
            reportPaths, ...
            templatesDirectory);

        if ~isempty(indexPath) && ...
                exist(indexPath, 'file') == 2

            web( ...
                indexPath, ...
                '-browser');

        end

        ut_setStatus( ...
            fig, ...
            'Report generated successfully.', ...
            'success');

        msgbox( ...
            'Report generated successfully.', ...
            'Generate Report');

    catch ME

        ut_setStatus( ...
            fig, ...
            'Report generation failed.', ...
            'error');

        errordlg( ...
            ME.message, ...
            'Report Error');

    end

end


function [frameName, framePath] = resolveTestFrame(fig, xmlPath)

    frameName = '';
    framePath = '';

    storedFramePath = getappdata( ...
        fig, ...
        'slxFilePath');

    if ~isempty(storedFramePath) && ...
            exist(storedFramePath, 'file') == 2

        framePath = storedFramePath;

        [~, frameName] = fileparts(framePath);

        return;

    end

    xmlFolder = fileparts(xmlPath);

    slxFiles = dir(fullfile( ...
        xmlFolder, ...
        '*.slx'));

    if isempty(slxFiles)
        return;
    end

    framePath = fullfile( ...
        xmlFolder, ...
        slxFiles(1).name);

    [~, frameName] = fileparts(framePath);

end


function value = getPopupValue(controlHandle)

    popupItems = get( ...
        controlHandle, ...
        'String');

    selectedIndex = get( ...
        controlHandle, ...
        'Value');

    if ischar(popupItems)

        value = popupItems;

        return;

    end

    if isempty(popupItems)

        value = '';

        return;

    end

    selectedIndex = max( ...
        1, ...
        min(selectedIndex, numel(popupItems)));

    value = popupItems{selectedIndex};

end


function isPlaceholder = isPlaceholderValue(value)

    isPlaceholder = isempty(value) || ...
        (~isempty(value) && value(1) == '<');

end


function items = normalizeListboxStrings(value)

    if isempty(value)

        items = {};

    elseif ischar(value)

        items = cellstr(value);

    else

        items = value;

    end

    items = items(:);

end


function value = getControlString(fig, appDataName)

    controlHandle = getApplicationControl( ...
        fig, ...
        appDataName);

    value = strtrim(get( ...
        controlHandle, ...
        'String'));

end


function controlHandle = getApplicationControl(fig, appDataName)

    controlHandle = getappdata( ...
        fig, ...
        appDataName);

    if isempty(controlHandle) || ...
            ~ishandle(controlHandle)

        error( ...
            'ut_callbacks:MissingUIControl', ...
            'Application UI control "%s" is unavailable.', ...
            appDataName);

    end

end


function setApplicationControl(fig, appDataName, varargin)

    controlHandle = getApplicationControl( ...
        fig, ...
        appDataName);

    set( ...
        controlHandle, ...
        varargin{:});

end


function updateBatchCount(fig)

    appData = guidata(fig);

    if isempty(appData) || ...
            ~isfield(appData, 'BatchRunView')

        return;

    end

    if ~isfield( ...
            appData.BatchRunView, ...
            'FileCountText')

        return;

    end

    fileCountText = ...
        appData.BatchRunView.FileCountText;

    if isempty(fileCountText) || ...
            ~ishandle(fileCountText)

        return;

    end

    batchPaths = getappdata( ...
        fig, ...
        'excelPathList');

    fileCount = numel(batchPaths);

    if fileCount == 1
        countLabel = '1 file';
    else
        countLabel = sprintf( ...
            '%d files', ...
            fileCount);
    end

    set( ...
        fileCountText, ...
        'String', ...
        countLabel);

end