function result = ut_generateCode(fig, frameName)
%UT_GENERATECODE Generate TargetLink code for the selected test frame.
%
% Inputs:
%   fig       - Main MBUT application figure handle.
%   frameName - Name of the loaded Simulink test frame.
%
% Output:
%   result    - True when TargetLink code generation succeeds.

    result = false;

    ut_setStatus( ...
        fig, ...
        'Generating code...', ...
        'working');

    excelFile = getappdata( ...
        fig, ...
        'mtcdXlsPath');

    if isempty(excelFile) || exist(excelFile, 'file') ~= 2
        error( ...
            'ut_generateCode:InvalidTestCaseFile', ...
            'A valid test case XML file is required.');
    end

    if nargin < 2 || isempty(frameName)
        error( ...
            'ut_generateCode:InvalidFrameName', ...
            'A valid test frame name is required.');
    end

    baseDirectory = fileparts(excelFile);

    logFilePath = fullfile( ...
        baseDirectory, ...
        'commandLog.txt');

    commandLog( ...
        logFilePath, ...
        'Code Generation Started.');

    previousDirectory = pwd;

    cleanupObject = onCleanup( ...
        @() cd(previousDirectory)); %#ok<NASGU>

    cd(baseDirectory);

    try

        subsystemHandles = dsdd( ...
            'Find', ...
            '/Subsystems', ...
            'ObjectKind', ...
            'Subsystem');

        for subsystemIndex = 1:length(subsystemHandles)

            dsdd( ...
                'Delete', ...
                subsystemHandles(subsystemIndex));

        end

        mainDialogHandles = find_system( ...
            frameName, ...
            'MaskType', ...
            'TL_MainDialog');

        if isempty(mainDialogHandles)

            error( ...
                'ut_generateCode:TargetLinkDialogNotFound', ...
                ['TargetLink Main Dialog was not found in ' ...
                 'the selected test frame.']);

        end

        tl_set( ...
            mainDialogHandles, ...
            'codecoveragelevel', ...
            2, ...
            'codeopt.cleancode', ...
            0, ...
            'logopt.globalloggingmode', ...
            1);

        buildCommand = sprintf( ...
            ['tl_build_host(''Model'', ''%s'', ' ...
             '''IncludeSubItems'', ''on'')'], ...
            frameName);

        buildOutput = evalc(buildCommand);

        symbolTableGenerated = ~isempty(strfind(buildOutput,'GENERATING SYMBOL TABLE SUCCEEDED'));

        symbolTableStarted = ...
            ~isempty(strfind( ...
                buildOutput, ...
                'GENERATING SYMBOL TABLE'));

        result = ...
            symbolTableGenerated && ...
            symbolTableStarted;

        if result

            commandLog( ...
                logFilePath, ...
                'Code Generation Successfully completed.');

            ut_setStatus( ...
                fig, ...
                'Code generation completed successfully.', ...
                'success');

        else

            commandLog( ...
                logFilePath, ...
                'Issue in Generating Code');

            ut_setStatus( ...
                fig, ...
                'Code generation failed.', ...
                'error');

        end

    catch ME

        commandLog( ...
            logFilePath, ...
            ['Code Generation Error: ' ME.message]);

        ut_setStatus( ...
            fig, ...
            'Code generation failed.', ...
            'error');

        rethrow(ME);

    end

end