function handles = view_BatchRun(parentPanel)
% VIEW_BATCHRUN Create the Batch Run user interface.
%
% Input:
%   parentPanel - Parent uipanel supplied by MainApplication.
%
% Output:
%   handles     - Structure containing view graphics handles.

    C.Background      = [0.945 0.953 0.965];
    C.Card            = [1.000 1.000 1.000];
    C.CardBorder      = [0.855 0.875 0.905];
    C.TextPrimary     = [0.105 0.125 0.160];
    C.TextSecondary   = [0.420 0.455 0.510];
    C.TextMuted       = [0.570 0.600 0.650];
    C.InputBackground = [0.975 0.980 0.988];
    C.Primary         = [0.125 0.350 0.620];
    C.DarkButton      = [0.120 0.145 0.185];
    C.SecondaryButton = [0.900 0.920 0.945];
    C.Divider         = [0.900 0.915 0.935];
    C.White           = [1 1 1];

    handles.MainPanel = uipanel( ...
        'Parent', parentPanel, ...
        'Units', 'normalized', ...
        'Position', [0 0 1 1], ...
        'BackgroundColor', C.Background, ...
        'BorderType', 'none');

    handles.BatchAxes = axes( ...
        'Parent', handles.MainPanel, ...
        'Units', 'normalized', ...
        'Position', [0.045 0.065 0.91 0.885], ...
        'XLim', [0 1], ...
        'YLim', [0 1], ...
        'Visible', 'off', ...
        'Color', 'none');

    rectangle( ...
        'Parent', handles.BatchAxes, ...
        'Position', [0.005 0.005 0.99 0.99], ...
        'Curvature', [0.01 0.01], ...
        'FaceColor', C.Card, ...
        'EdgeColor', C.CardBorder, ...
        'LineWidth', 1);

    text( ...
        0.045, 0.925, ...
        'Batch Run', ...
        'Parent', handles.BatchAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 14, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'Interpreter', 'none');

    text( ...
        0.045, 0.875, ...
        'Manage multiple test case files and execute batch operations.', ...
        'Parent', handles.BatchAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 9.5, ...
        'Color', C.TextSecondary, ...
        'Interpreter', 'none');

    line( ...
        [0.045 0.955], ...
        [0.830 0.830], ...
        'Parent', handles.BatchAxes, ...
        'Color', C.Divider, ...
        'LineWidth', 1);

    text( ...
        0.045, 0.775, ...
        'Test Case Files', ...
        'Parent', handles.BatchAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'Interpreter', 'none');

    handles.FileCountText = text( ...
        0.955, 0.775, ...
        '0 files', ...
        'Parent', handles.BatchAxes, ...
        'HorizontalAlignment', 'right', ...
        'FontName', 'Segoe UI', ...
        'FontSize', 9, ...
        'Color', C.TextMuted, ...
        'Interpreter', 'none');

    handles.ExcelPathListBox = uicontrol( ...
        'Parent', handles.MainPanel, ...
        'Style', 'listbox', ...
        'Units', 'normalized', ...
        'Position', [0.085 0.295 0.830 0.405], ...
        'String', {}, ...
        'Min', 1, ...
        'Max', 10, ...
        'Value', 1, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'ForegroundColor', C.TextPrimary, ...
        'BackgroundColor', C.InputBackground, ...
        'Callback', @(s,e)ut_callbacks('batchSelectionChanged', ancestor(handles.MainPanel, 'figure')));

    handles.AddExcelButton = createRoundedButton( ...
        handles.BatchAxes, ...
        [0.045 0.125 0.180 0.075], ...
        'Add Excel', ...
        C.Primary, ...
        C.White, ...
        @(s,e)ut_callbacks('addBatchFile', ancestor(handles.MainPanel, 'figure')));

    handles.DeleteButton = createRoundedButton( ...
        handles.BatchAxes, ...
        [0.245 0.125 0.150 0.075], ...
        'Delete', ...
        C.SecondaryButton, ...
        C.TextPrimary, ...
        @(s,e)ut_callbacks('deleteBatchFile', ancestor(handles.MainPanel, 'figure')));

    line( ...
        [0.425 0.425], ...
        [0.130 0.205], ...
        'Parent', handles.BatchAxes, ...
        'Color', C.Divider, ...
        'LineWidth', 1);

    handles.ExecuteSimulationButton = createRoundedButton( ...
        handles.BatchAxes, ...
        [0.465 0.125 0.180 0.075], ...
        'Execute Simulation', ...
        C.Primary, ...
        C.White, ...
        @(s,e)ut_callbacks('executeBatch', ancestor(handles.MainPanel, 'figure')));

    handles.BatchRunButton = createRoundedButton( ...
        handles.BatchAxes, ...
        [0.665 0.125 0.130 0.075], ...
        'Batch Run', ...
        C.DarkButton, ...
        C.White, ...
        @(s,e)ut_callbacks('automaticBatchRun', ancestor(handles.MainPanel, 'figure')));

    handles.TestCasesRunButton = createRoundedButton( ...
        handles.BatchAxes, ...
        [0.815 0.125 0.140 0.075], ...
        'Test Cases Run', ...
        C.DarkButton, ...
        C.White, ...
        @(s,e)ut_callbacks('runBatchTestCases', ancestor(handles.MainPanel, 'figure')));

    setappdata(handles.MainPanel, 'ExcelPathList', {});
    setappdata(handles.MainPanel, 'SelectedExcelIdx', []);

    updateFileList();


    function addExcelCallback(~, ~)

        [fileName, pathName] = uigetfile( ...
            { ...
                '*.xlsx;*.xls', 'Excel Files (*.xlsx, *.xls)'; ...
                '*.*', 'All Files (*.*)' ...
            }, ...
            'Select Test Case Excel File', ...
            'MultiSelect', 'on');

        if isequal(fileName, 0)
            return;
        end

        excelPathList = getappdata( ...
            handles.MainPanel, ...
            'ExcelPathList');

        if isempty(excelPathList)
            excelPathList = {};
        end

        if ischar(fileName)

            newPath = fullfile(pathName, fileName);

            if ~any(strcmp(excelPathList, newPath))
                excelPathList{end + 1} = newPath;
            end

        else

            for i = 1:length(fileName)

                newPath = fullfile(pathName, fileName{i});

                if ~any(strcmp(excelPathList, newPath))
                    excelPathList{end + 1} = newPath;
                end

            end

        end

        setappdata( ...
            handles.MainPanel, ...
            'ExcelPathList', ...
            excelPathList);

        setappdata( ...
            handles.MainPanel, ...
            'SelectedExcelIdx', ...
            []);

        updateFileList();

        setStatus('Test case files added.', 'success');

    end


    function onExcelPathSelected(source, ~)

        excelPathList = getappdata( ...
            handles.MainPanel, ...
            'ExcelPathList');

        if isempty(excelPathList)

            setappdata( ...
                handles.MainPanel, ...
                'SelectedExcelIdx', ...
                []);

            return;

        end

        selectedIndices = get(source, 'Value');

        selectedIndices = selectedIndices( ...
            selectedIndices >= 1 & ...
            selectedIndices <= length(excelPathList));

        setappdata( ...
            handles.MainPanel, ...
            'SelectedExcelIdx', ...
            selectedIndices);

    end


    function deleteSelectedExcel(~, ~)

        excelPathList = getappdata( ...
            handles.MainPanel, ...
            'ExcelPathList');

        if isempty(excelPathList)
            return;
        end

        selectedIndices = get( ...
            handles.ExcelPathListBox, ...
            'Value');

        selectedIndices = selectedIndices( ...
            selectedIndices >= 1 & ...
            selectedIndices <= length(excelPathList));

        if isempty(selectedIndices)
            return;
        end

        excelPathList(selectedIndices) = [];

        setappdata( ...
            handles.MainPanel, ...
            'ExcelPathList', ...
            excelPathList);

        setappdata( ...
            handles.MainPanel, ...
            'SelectedExcelIdx', ...
            []);

        updateFileList();

        setStatus('Selected files removed.', 'success');

    end


    function onExecuteSimulation(~, ~)

        excelPathList = getappdata( ...
            handles.MainPanel, ...
            'ExcelPathList');

        if isempty(excelPathList)

            setStatus( ...
                'Add at least one test case Excel file.', ...
                'warning');

            errordlg( ...
                'Add at least one test case Excel file.', ...
                'Batch Run');

            return;

        end

        setStatus('Executing simulation...', 'working');

        drawnow;

        disp('Execute Simulation');
        disp(excelPathList);

    end


    function onAutomaticBatchRun(~, ~)

        excelPathList = getappdata( ...
            handles.MainPanel, ...
            'ExcelPathList');

        if isempty(excelPathList)

            setStatus( ...
                'Add at least one test case Excel file.', ...
                'warning');

            errordlg( ...
                'Add at least one test case Excel file.', ...
                'Batch Run');

            return;

        end

        setStatus('Batch run in progress...', 'working');

        drawnow;

        disp('Automatic Batch Run');
        disp(excelPathList);

    end


    function onRunTestCases(~, ~)

        excelPathList = getappdata( ...
            handles.MainPanel, ...
            'ExcelPathList');

        if isempty(excelPathList)

            setStatus( ...
                'Add at least one test case Excel file.', ...
                'warning');

            errordlg( ...
                'Add at least one test case Excel file.', ...
                'Batch Run');

            return;

        end

        setStatus('Running test cases...', 'working');

        drawnow;

        disp('Test Cases Run');
        disp(excelPathList);

    end


    function updateFileList()

        excelPathList = getappdata( ...
            handles.MainPanel, ...
            'ExcelPathList');

        if isempty(excelPathList)

            set(handles.ExcelPathListBox, ...
                'String', {}, ...
                'Value', 1);

        else

            set(handles.ExcelPathListBox, ...
                'String', excelPathList, ...
                'Value', 1);

        end

        fileCount = length(excelPathList);

        if fileCount == 1
            countString = '1 file';
        else
            countString = sprintf('%d files', fileCount);
        end

        set(handles.FileCountText, ...
            'String', countString);

    end


    function setStatus(statusMessage, statusType)

        if nargin < 2
            statusType = 'ready';
        end

        hFigure = ancestor(handles.MainPanel, 'figure');

        if isempty(hFigure) || ~ishandle(hFigure)
            return;
        end

        appData = guidata(hFigure);

        if isempty(appData) || ...
                ~isstruct(appData) || ...
                ~isfield(appData, 'StatusText') || ...
                ~isfield(appData, 'StatusIndicator')

            return;

        end

        switch lower(statusType)

            case 'working'
                indicatorColor = [0.125 0.350 0.620];

            case 'success'
                indicatorColor = [0.145 0.520 0.330];

            case 'warning'
                indicatorColor = [0.850 0.560 0.120];

            case 'error'
                indicatorColor = [0.720 0.220 0.220];

            otherwise
                indicatorColor = [0.145 0.520 0.330];

        end

        set(appData.StatusText, ...
            'String', statusMessage);

        set(appData.StatusIndicator, ...
            'ForegroundColor', indicatorColor);

        drawnow;

    end


    function buttonHandles = createRoundedButton( ...
            parentAxes, ...
            position, ...
            buttonText, ...
            backgroundColor, ...
            textColor, ...
            callbackFunction)

        buttonHandles = struct();

        buttonHandles.Background = rectangle( ...
            'Parent', parentAxes, ...
            'Position', position, ...
            'Curvature', [0.08 0.20], ...
            'FaceColor', backgroundColor, ...
            'EdgeColor', backgroundColor, ...
            'LineWidth', 1, ...
            'ButtonDownFcn', callbackFunction);

        textX = position(1) + position(3) / 2;
        textY = position(2) + position(4) / 2;

        buttonHandles.Text = text( ...
            textX, ...
            textY, ...
            buttonText, ...
            'Parent', parentAxes, ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', ...
            'FontName', 'Segoe UI', ...
            'FontSize', 10, ...
            'FontWeight', 'bold', ...
            'Color', textColor, ...
            'Interpreter', 'none', ...
            'ButtonDownFcn', callbackFunction);

    end

end
