function handles = view_ModelSetup(parentPanel)
% VIEW_MODELSETUP Create the Model Setup user interface.
%
% Input:
%   parentPanel - Parent uipanel supplied by MainApplication.
%
% Output:
%   handles     - Structure containing view graphics handles.

    C.Background      = [0.945 0.953 0.965];
    C.Card            = [1.000 1.000 1.000];
    C.CardBorder      = [0.855 0.875 0.905];
    C.TextPrimary     = [0.105 0.125 0.160];
    C.TextSecondary   = [0.420 0.455 0.510];
    C.InputBackground = [0.975 0.980 0.988];
    C.Primary         = [0.125 0.350 0.620];
    C.DarkButton      = [0.120 0.145 0.185];
    C.SecondaryButton = [0.900 0.920 0.945];
    C.Divider         = [0.900 0.915 0.935];
    C.White           = [1 1 1];

    handles.MainPanel = uipanel( ...
        'Parent', parentPanel, ...
        'Units', 'normalized', ...
        'Position', [0 0 1 1], ...
        'BackgroundColor', C.Background, ...
        'BorderType', 'none');

    handles.ConfigAxes = axes( ...
        'Parent', handles.MainPanel, ...
        'Units', 'normalized', ...
        'Position', [0.045 0.405 0.91 0.540], ...
        'XLim', [0 1], ...
        'YLim', [0 1], ...
        'Visible', 'off', ...
        'Color', 'none');

    rectangle( ...
        'Parent', handles.ConfigAxes, ...
        'Position', [0.005 0.005 0.99 0.99], ...
        'Curvature', [0.01 0.01], ...
        'FaceColor', C.Card, ...
        'EdgeColor', C.CardBorder, ...
        'LineWidth', 1);

    text( ...
        0.045, 0.885, ...
        'Model Configuration', ...
        'Parent', handles.ConfigAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 14, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'Interpreter', 'none');

    text( ...
        0.045, 0.815, ...
        'Configure the Simulink model and workspace for unit testing.', ...
        'Parent', handles.ConfigAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 9.5, ...
        'Color', C.TextSecondary, ...
        'Interpreter', 'none');

    line( ...
        [0.045 0.955], ...
        [0.755 0.755], ...
        'Parent', handles.ConfigAxes, ...
        'Color', C.Divider, ...
        'LineWidth', 1);

    text( ...
        0.045, 0.660, ...
        'Main Model', ...
        'Parent', handles.ConfigAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'VerticalAlignment', 'middle', ...
        'Interpreter', 'none');

    handles.MainModelEdit = uicontrol( ...
        'Parent', handles.MainPanel, ...
        'Style', 'edit', ...
        'Units', 'normalized', ...
        'Position', [0.22 0.730 0.555 0.052], ...
        'String', '', ...
        'HorizontalAlignment', 'left', ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'ForegroundColor', C.TextPrimary, ...
        'BackgroundColor', C.InputBackground);

    handles.MainModelBrowse = createRoundedButton( ...
        handles.ConfigAxes, ...
        [0.825 0.605 0.13 0.105], ...
        'Browse', ...
        C.SecondaryButton, ...
        C.TextPrimary, ...
        @(s,e)ut_callbacks('browseMainModel', ancestor(handles.MainPanel, 'figure')));

    text( ...
        0.045, 0.475, ...
        'Submodule', ...
        'Parent', handles.ConfigAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'VerticalAlignment', 'middle', ...
        'Interpreter', 'none');

    handles.SubmoduleEdit = uicontrol( ...
        'Parent', handles.MainPanel, ...
        'Style', 'edit', ...
        'Units', 'normalized', ...
        'Position', [0.22 0.630 0.555 0.052], ...
        'String', '', ...
        'HorizontalAlignment', 'left', ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'ForegroundColor', C.TextPrimary, ...
        'BackgroundColor', C.InputBackground);

    handles.SubmoduleBrowse = createRoundedButton( ...
        handles.ConfigAxes, ...
        [0.825 0.420 0.13 0.105], ...
        'Browse', ...
        C.SecondaryButton, ...
        C.TextPrimary, ...
        @(s,e)ut_callbacks('browseSubmodule', ancestor(handles.MainPanel, 'figure')));

    text( ...
        0.045, 0.290, ...
        'Save Path', ...
        'Parent', handles.ConfigAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'VerticalAlignment', 'middle', ...
        'Interpreter', 'none');

    handles.SavePathEdit = uicontrol( ...
        'Parent', handles.MainPanel, ...
        'Style', 'edit', ...
        'Units', 'normalized', ...
        'Position', [0.22 0.530 0.555 0.052], ...
        'String', '', ...
        'HorizontalAlignment', 'left', ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'ForegroundColor', C.TextPrimary, ...
        'BackgroundColor', C.InputBackground);

    handles.SavePathBrowse = createRoundedButton( ...
        handles.ConfigAxes, ...
        [0.825 0.235 0.13 0.105], ...
        'Browse', ...
        C.SecondaryButton, ...
        C.TextPrimary, ...
        @(s,e)ut_callbacks('browseSavePath', ancestor(handles.MainPanel, 'figure')));

    handles.SaveButton = createRoundedButton( ...
        handles.ConfigAxes, ...
        [0.40 0.060 0.165 0.115], ...
        'Save Information', ...
        C.Primary, ...
        C.White, ...
        @(s,e)ut_callbacks('saveModelInfo', ancestor(handles.MainPanel, 'figure')));

    handles.ActionAxes = axes( ...
        'Parent', handles.MainPanel, ...
        'Units', 'normalized', ...
        'Position', [0.045 0.120 0.91 0.250], ...
        'XLim', [0 1], ...
        'YLim', [0 1], ...
        'Visible', 'off', ...
        'Color', 'none');

    rectangle( ...
        'Parent', handles.ActionAxes, ...
        'Position', [0.005 0.01 0.99 0.98], ...
        'Curvature', [0.01 0.01], ...
        'FaceColor', C.Card, ...
        'EdgeColor', C.CardBorder, ...
        'LineWidth', 1);

    text( ...
        0.045, 0.755, ...
        'Test Frame', ...
        'Parent', handles.ActionAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 13, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'Interpreter', 'none');

    text( ...
        0.045, 0.590, ...
        'Create a new test frame or continue with an existing configuration.', ...
        'Parent', handles.ActionAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 9.5, ...
        'Color', C.TextSecondary, ...
        'Interpreter', 'none');

    line( ...
        [0.045 0.955], ...
        [0.500 0.500], ...
        'Parent', handles.ActionAxes, ...
        'Color', C.Divider, ...
        'LineWidth', 1);

    handles.GenerateButton = createRoundedButton( ...
        handles.ActionAxes, ...
        [0.045 0.135 0.435 0.285], ...
        'Generate Test Frame', ...
        C.Primary, ...
        C.White, ...
        @(s,e)ut_callbacks('generateTestFrame', ancestor(handles.MainPanel, 'figure')));

    handles.OpenButton = createRoundedButton( ...
        handles.ActionAxes, ...
        [0.515 0.135 0.440 0.285], ...
        'Open Existing Test Frame', ...
        C.DarkButton, ...
        C.White, ...
        @(s,e)ut_callbacks('openTestFrame', ancestor(handles.MainPanel, 'figure')));


    function browseMainModel(~, ~)

        [fileName, pathName] = uigetfile( ...
            {'*.slx;*.mdl', ...
             'Simulink Models (*.slx, *.mdl)'}, ...
            'Select Main Model');

        if isequal(fileName, 0)
            return;
        end

        mainModelPath = fullfile(pathName, fileName);

        set(handles.MainModelEdit, ...
            'String', mainModelPath);

        setStatus('Main model selected.', 'success');

    end


    function browseSubmodule(~, ~)

        [fileName, pathName] = uigetfile( ...
            {'*.slx;*.mdl', ...
             'Simulink Models (*.slx, *.mdl)'}, ...
            'Select Submodule');

        if isequal(fileName, 0)
            return;
        end

        submodulePath = fullfile(pathName, fileName);

        set(handles.SubmoduleEdit, ...
            'String', submodulePath);

        setStatus('Submodule selected.', 'success');

    end


    function browseSavePath(~, ~)

        selectedPath = uigetdir( ...
            pwd, ...
            'Select Save Location');

        if isequal(selectedPath, 0)
            return;
        end

        set(handles.SavePathEdit, ...
            'String', selectedPath);

        setStatus('Save path selected.', 'success');

    end


    function saveInfo(~, ~)

        mainModel = strtrim( ...
            get(handles.MainModelEdit, 'String'));

        submodule = strtrim( ...
            get(handles.SubmoduleEdit, 'String'));

        savePath = strtrim( ...
            get(handles.SavePathEdit, 'String'));

        if isempty(mainModel)

            setStatus( ...
                'Please select the Main Model.', ...
                'warning');

            errordlg( ...
                'Please select the Main Model.', ...
                'Model Setup');

            return;

        end

        if isempty(submodule)

            setStatus( ...
                'Please select the Submodule.', ...
                'warning');

            errordlg( ...
                'Please select the Submodule.', ...
                'Model Setup');

            return;

        end

        if isempty(savePath)

            setStatus( ...
                'Please select the Save Path.', ...
                'warning');

            errordlg( ...
                'Please select the Save Path.', ...
                'Model Setup');

            return;

        end

        modelInfo = struct();

        modelInfo.MainModel = mainModel;
        modelInfo.Submodule = submodule;
        modelInfo.SavePath  = savePath;

        setappdata( ...
            handles.MainPanel, ...
            'ModelInfo', ...
            modelInfo);

        setStatus( ...
            'Model configuration saved successfully.', ...
            'success');

        msgbox( ...
            'Model configuration saved successfully.', ...
            'Model Setup');

    end


    function generateTestFrameCallback(~, ~)

        if ~isappdata(handles.MainPanel, 'ModelInfo')

            setStatus( ...
                'Save the model configuration before generating the test frame.', ...
                'warning');

            errordlg( ...
                ['Save the model configuration before ' ...
                 'generating the test frame.'], ...
                'Generate Test Frame');

            return;

        end

        modelInfo = getappdata( ...
            handles.MainPanel, ...
            'ModelInfo');

        setStatus( ...
            'Generating test frame...', ...
            'working');

        drawnow;

        disp('Generate Test Frame');
        disp(modelInfo);

        try

            % generateTestFrame(modelInfo);

            setStatus( ...
                'Test frame generated successfully.', ...
                'success');

        catch ME

            setStatus( ...
                'Test frame generation failed.', ...
                'error');

            errordlg( ...
                ME.message, ...
                'Generate Test Frame');

        end

    end


    function openExistingTestFrameCallback(~, ~)

        [fileName, pathName] = uigetfile( ...
            {'*.*', 'All Files (*.*)'}, ...
            'Select Existing Test Frame');

        if isequal(fileName, 0)
            return;
        end

        testFramePath = fullfile(pathName, fileName);

        setStatus( ...
            'Opening existing test frame...', ...
            'working');

        drawnow;

        try

            disp('Open Existing Test Frame');
            disp(testFramePath);

            % openExistingTestFrame(testFramePath);

            setStatus( ...
                'Existing test frame opened successfully.', ...
                'success');

        catch ME

            setStatus( ...
                'Unable to open the existing test frame.', ...
                'error');

            errordlg( ...
                ME.message, ...
                'Open Existing Test Frame');

        end

    end


    function setStatus(statusMessage, statusType)

        if nargin < 2
            statusType = 'ready';
        end

        hFigure = ancestor(handles.MainPanel, 'figure');

        if isempty(hFigure) || ~ishandle(hFigure)
            return;
        end

        appData = guidata(hFigure);

        if isempty(appData) || ...
                ~isstruct(appData) || ...
                ~isfield(appData, 'StatusText') || ...
                ~isfield(appData, 'StatusIndicator')

            return;

        end

        switch lower(statusType)

            case 'working'
                indicatorColor = [0.125 0.350 0.620];

            case 'success'
                indicatorColor = [0.145 0.520 0.330];

            case 'warning'
                indicatorColor = [0.850 0.560 0.120];

            case 'error'
                indicatorColor = [0.720 0.220 0.220];

            otherwise
                indicatorColor = [0.145 0.520 0.330];

        end

        set(appData.StatusText, ...
            'String', statusMessage);

        set(appData.StatusIndicator, ...
            'ForegroundColor', indicatorColor);

        drawnow;

    end


    function buttonHandles = createRoundedButton( ...
            parentAxes, ...
            position, ...
            buttonText, ...
            backgroundColor, ...
            textColor, ...
            callbackFunction)

        buttonHandles = struct();

        buttonHandles.Background = rectangle( ...
            'Parent', parentAxes, ...
            'Position', position, ...
            'Curvature', [0.08 0.20], ...
            'FaceColor', backgroundColor, ...
            'EdgeColor', backgroundColor, ...
            'LineWidth', 1, ...
            'ButtonDownFcn', callbackFunction);

        textX = position(1) + position(3) / 2;
        textY = position(2) + position(4) / 2;

        buttonHandles.Text = text( ...
            textX, ...
            textY, ...
            buttonText, ...
            'Parent', parentAxes, ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', ...
            'FontName', 'Segoe UI', ...
            'FontSize', 10, ...
            'FontWeight', 'bold', ...
            'Color', textColor, ...
            'Interpreter', 'none', ...
            'ButtonDownFcn', callbackFunction);

    end

end
