function handles = view_TestCaseGeneration(parentPanel)

    C.Background      = [0.945 0.953 0.965];
    C.Card            = [1.000 1.000 1.000];
    C.CardBorder      = [0.855 0.875 0.905];
    C.TextPrimary     = [0.105 0.125 0.160];
    C.TextSecondary   = [0.420 0.455 0.510];
    C.Primary         = [0.125 0.350 0.620];
    C.Divider         = [0.900 0.915 0.935];
    C.White           = [1 1 1];

    handles.MainPanel = uipanel( ...
        'Parent', parentPanel, ...
        'Units', 'normalized', ...
        'Position', [0 0 1 1], ...
        'BackgroundColor', C.Background, ...
        'BorderType', 'none');

    handles.GenerationAxes = axes( ...
        'Parent', handles.MainPanel, ...
        'Units', 'normalized', ...
        'Position', [0.045 0.180 0.91 0.650], ...
        'XLim', [0 1], ...
        'YLim', [0 1], ...
        'Visible', 'off', ...
        'Color', 'none');

    rectangle( ...
        'Parent', handles.GenerationAxes, ...
        'Position', [0.005 0.005 0.99 0.99], ...
        'Curvature', [0.01 0.01], ...
        'FaceColor', C.Card, ...
        'EdgeColor', C.CardBorder, ...
        'LineWidth', 1);

    text( ...
        0.045, 0.875, ...
        'Test Case Generation', ...
        'Parent', handles.GenerationAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 14, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'Interpreter', 'none');

    text( ...
        0.045, 0.795, ...
        'Launch the configured test case generation workflow.', ...
        'Parent', handles.GenerationAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 9.5, ...
        'Color', C.TextSecondary, ...
        'Interpreter', 'none');

    line( ...
        [0.045 0.955], ...
        [0.720 0.720], ...
        'Parent', handles.GenerationAxes, ...
        'Color', C.Divider, ...
        'LineWidth', 1);

    text( ...
        0.500, 0.555, ...
        'Generate test cases using the configured external generator.', ...
        'Parent', handles.GenerationAxes, ...
        'HorizontalAlignment', 'center', ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'Color', C.TextSecondary, ...
        'Interpreter', 'none');

    handles.GenerateButton = createRoundedButton( ...
        handles.GenerationAxes, ...
        [0.315 0.315 0.370 0.135], ...
        'Run Test Case Generator', ...
        C.Primary, ...
        C.White, ...
        @(s,e)ut_callbacks( ...
            'runTestCaseGenerator', ...
            ancestor(handles.MainPanel, 'figure')));

    function buttonHandles = createRoundedButton( ...
            parentAxes, position, buttonText, ...
            backgroundColor, textColor, callbackFunction)

        buttonHandles = struct();

        buttonHandles.Background = rectangle( ...
            'Parent', parentAxes, ...
            'Position', position, ...
            'Curvature', [0.08 0.20], ...
            'FaceColor', backgroundColor, ...
            'EdgeColor', backgroundColor, ...
            'LineWidth', 1, ...
            'ButtonDownFcn', callbackFunction);

        textX = position(1) + position(3) / 2;
        textY = position(2) + position(4) / 2;

        buttonHandles.Text = text( ...
            textX, textY, buttonText, ...
            'Parent', parentAxes, ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', ...
            'FontName', 'Segoe UI', ...
            'FontSize', 10, ...
            'FontWeight', 'bold', ...
            'Color', textColor, ...
            'Interpreter', 'none', ...
            'ButtonDownFcn', callbackFunction);

    end

end
