function handles = view_PlotAndReport(parentPanel)
% VIEW_PLOTANDREPORT Create the Plot and Report view.
%
% Input:
%   parentPanel - Parent uipanel supplied by MainApplication.
%
% Output:
%   handles     - Structure containing view graphics handles.

    C.Background      = [0.945 0.953 0.965];
    C.Card            = [1.000 1.000 1.000];
    C.CardBorder      = [0.855 0.875 0.905];
    C.TextPrimary     = [0.105 0.125 0.160];
    C.TextSecondary   = [0.420 0.455 0.510];
    C.TextMuted       = [0.570 0.600 0.650];
    C.InputBackground = [0.975 0.980 0.988];
    C.Primary         = [0.125 0.350 0.620];
    C.DarkButton      = [0.120 0.145 0.185];
    C.Divider         = [0.900 0.915 0.935];
    C.White           = [1 1 1];

    handles.MainPanel = uipanel( ...
        'Parent', parentPanel, ...
        'Units', 'normalized', ...
        'Position', [0 0 1 1], ...
        'BackgroundColor', C.Background, ...
        'BorderType', 'none');

    handles.PlotAxes = axes( ...
        'Parent', handles.MainPanel, ...
        'Units', 'normalized', ...
        'Position', [0.045 0.555 0.91 0.395], ...
        'XLim', [0 1], ...
        'YLim', [0 1], ...
        'Visible', 'off', ...
        'Color', 'none');

    rectangle( ...
        'Parent', handles.PlotAxes, ...
        'Position', [0.005 0.01 0.99 0.98], ...
        'Curvature', [0.01 0.01], ...
        'FaceColor', C.Card, ...
        'EdgeColor', C.CardBorder, ...
        'LineWidth', 1);

    text( ...
        0.045, 0.875, ...
        'Signal Plotting', ...
        'Parent', handles.PlotAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 13, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'Interpreter', 'none');

    text( ...
        0.045, 0.785, ...
        'Select the test sequence, signal and comparison mode for analysis.', ...
        'Parent', handles.PlotAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 9.5, ...
        'Color', C.TextSecondary, ...
        'Interpreter', 'none');

    line( ...
        [0.045 0.955], ...
        [0.710 0.710], ...
        'Parent', handles.PlotAxes, ...
        'Color', C.Divider, ...
        'LineWidth', 1);

    text( ...
        0.045, 0.585, ...
        'TS Folder', ...
        'Parent', handles.PlotAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'Interpreter', 'none');

    handles.FolderDropdown = uicontrol( ...
        'Parent', handles.MainPanel, ...
        'Style', 'popupmenu', ...
        'Units', 'normalized', ...
        'Position', [0.085 0.690 0.245 0.050], ...
        'String', {'<TS Folder>'}, ...
        'Value', 1, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'ForegroundColor', C.TextPrimary, ...
        'BackgroundColor', C.InputBackground, ...
        'Callback', @(s,e)ut_callbacks('plotFolderChanged', ancestor(handles.MainPanel, 'figure')));

    text( ...
        0.365, 0.585, ...
        'Signal', ...
        'Parent', handles.PlotAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'Interpreter', 'none');

    handles.SignalDropdown = uicontrol( ...
        'Parent', handles.MainPanel, ...
        'Style', 'popupmenu', ...
        'Units', 'normalized', ...
        'Position', [0.375 0.690 0.245 0.050], ...
        'String', {'<Signal>'}, ...
        'Value', 1, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'ForegroundColor', C.TextPrimary, ...
        'BackgroundColor', C.InputBackground, ...
        'Callback', @(s,e)ut_callbacks('plotFolderChanged', ancestor(handles.MainPanel, 'figure')));

    text( ...
        0.685, 0.585, ...
        'Compare', ...
        'Parent', handles.PlotAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'Interpreter', 'none');

    handles.CompareDropdown = uicontrol( ...
        'Parent', handles.MainPanel, ...
        'Style', 'popupmenu', ...
        'Units', 'normalized', ...
        'Position', [0.665 0.690 0.245 0.050], ...
        'String', { ...
            'MIL vs Expected', ...
            'MIL vs SIL'}, ...
        'Value', 1, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'ForegroundColor', C.TextPrimary, ...
        'BackgroundColor', C.InputBackground);

    handles.PlotSignalButton = createRoundedButton( ...
        handles.PlotAxes, ...
        [0.365 0.145 0.270 0.150], ...
        'Plot Signal', ...
        C.Primary, ...
        C.White, ...
        @(s,e)ut_callbacks('plotSignal', ancestor(handles.MainPanel, 'figure')));

    handles.ReportAxes = axes( ...
        'Parent', handles.MainPanel, ...
        'Units', 'normalized', ...
        'Position', [0.045 0.065 0.91 0.455], ...
        'XLim', [0 1], ...
        'YLim', [0 1], ...
        'Visible', 'off', ...
        'Color', 'none');

    rectangle( ...
        'Parent', handles.ReportAxes, ...
        'Position', [0.005 0.01 0.99 0.98], ...
        'Curvature', [0.01 0.01], ...
        'FaceColor', C.Card, ...
        'EdgeColor', C.CardBorder, ...
        'LineWidth', 1);

    text( ...
        0.045, 0.875, ...
        'Coverage Reporting', ...
        'Parent', handles.ReportAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 13, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'Interpreter', 'none');

    text( ...
        0.045, 0.795, ...
        'Configure the target coverage and generate the simulation report.', ...
        'Parent', handles.ReportAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 9.5, ...
        'Color', C.TextSecondary, ...
        'Interpreter', 'none');

    line( ...
        [0.045 0.955], ...
        [0.720 0.720], ...
        'Parent', handles.ReportAxes, ...
        'Color', C.Divider, ...
        'LineWidth', 1);

    text( ...
        0.045, 0.605, ...
        'Report Configuration', ...
        'Parent', handles.ReportAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'Interpreter', 'none');

    text( ...
        0.045, 0.445, ...
        'Target Coverage', ...
        'Parent', handles.ReportAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'VerticalAlignment', 'middle', ...
        'Interpreter', 'none');

    handles.TargetCoverageEdit = uicontrol( ...
        'Parent', handles.MainPanel, ...
        'Style', 'edit', ...
        'Units', 'normalized', ...
        'Position', [0.225 0.240 0.220 0.050], ...
        'String', '80', ...
        'HorizontalAlignment', 'left', ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'ForegroundColor', C.TextPrimary, ...
        'BackgroundColor', C.InputBackground);

    text( ...
        0.455, 0.445, ...
        '%', ...
        'Parent', handles.ReportAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'Color', C.TextSecondary, ...
        'VerticalAlignment', 'middle');

    text( ...
        0.045, 0.245, ...
        'Coverage Type', ...
        'Parent', handles.ReportAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'VerticalAlignment', 'middle', ...
        'Interpreter', 'none');

    handles.CoverageTypeDropdown = uicontrol( ...
        'Parent', handles.MainPanel, ...
        'Style', 'popupmenu', ...
        'Units', 'normalized', ...
        'Position', [0.225 0.150 0.220 0.050], ...
        'String', { ...
            'No Coverage', ...
            'Statement Coverage (C0)', ...
            'Decision Coverage (C1)'}, ...
        'Value', 1, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'ForegroundColor', C.TextPrimary, ...
        'BackgroundColor', C.InputBackground);

    line( ...
        [0.565 0.565], ...
        [0.150 0.605], ...
        'Parent', handles.ReportAxes, ...
        'Color', C.Divider, ...
        'LineWidth', 1);

    text( ...
        0.620, 0.605, ...
        'Report Generation', ...
        'Parent', handles.ReportAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'Interpreter', 'none');

    text( ...
        0.620, 0.500, ...
        {'Generate a structured HTML report using'; ...
         'the selected coverage configuration.'}, ...
        'Parent', handles.ReportAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 9.5, ...
        'Color', C.TextSecondary, ...
        'Interpreter', 'none', ...
        'VerticalAlignment', 'top');

    handles.GenerateReportButton = createRoundedButton( ...
        handles.ReportAxes, ...
        [0.620 0.175 0.335 0.150], ...
        'Generate Report', ...
        C.DarkButton, ...
        C.White, ...
        @(s,e)ut_callbacks('generateReport', ancestor(handles.MainPanel, 'figure')));

    setappdata(handles.MainPanel, 'TsFolders', {});
    setappdata(handles.MainPanel, 'SelectedSignal', '');

    populateTsFolders();


    function onFolderChanged(~, ~)

        folderOptions = get( ...
            handles.FolderDropdown, ...
            'String');

        folderIndex = get( ...
            handles.FolderDropdown, ...
            'Value');

        if isempty(folderOptions)
            return;
        end

        if ischar(folderOptions)
            selectedFolder = folderOptions;
        else
            selectedFolder = folderOptions{folderIndex};
        end

        if strcmp(selectedFolder, '<TS Folder>')

            set(handles.SignalDropdown, ...
                'String', {'<Signal>'}, ...
                'Value', 1);

            setappdata( ...
                handles.MainPanel, ...
                'SelectedSignal', ...
                '');

            setStatus( ...
                'Select a TS folder for signal analysis.', ...
                'ready');

            return;

        end

        setStatus( ...
            'Loading signals from the selected TS folder...', ...
            'working');

        drawnow;

        disp('Selected TS Folder');
        disp(selectedFolder);

        setStatus( ...
            'TS folder selected.', ...
            'success');

    end


    function onSignalChanged(~, ~)

        signalOptions = get( ...
            handles.SignalDropdown, ...
            'String');

        signalIndex = get( ...
            handles.SignalDropdown, ...
            'Value');

        if isempty(signalOptions)
            return;
        end

        if ischar(signalOptions)
            selectedSignal = signalOptions;
        else
            selectedSignal = signalOptions{signalIndex};
        end

        setappdata( ...
            handles.MainPanel, ...
            'SelectedSignal', ...
            selectedSignal);

        if ~strcmp(selectedSignal, '<Signal>')

            setStatus( ...
                'Signal selected for analysis.', ...
                'success');

        end

    end


    function onPlotSignalCallback(~, ~)

        folderOptions = get( ...
            handles.FolderDropdown, ...
            'String');

        folderIndex = get( ...
            handles.FolderDropdown, ...
            'Value');

        signalOptions = get( ...
            handles.SignalDropdown, ...
            'String');

        signalIndex = get( ...
            handles.SignalDropdown, ...
            'Value');

        compareOptions = get( ...
            handles.CompareDropdown, ...
            'String');

        compareIndex = get( ...
            handles.CompareDropdown, ...
            'Value');

        if ischar(folderOptions)
            selectedFolder = folderOptions;
        else
            selectedFolder = folderOptions{folderIndex};
        end

        if ischar(signalOptions)
            selectedSignal = signalOptions;
        else
            selectedSignal = signalOptions{signalIndex};
        end

        if ischar(compareOptions)
            selectedCompare = compareOptions;
        else
            selectedCompare = compareOptions{compareIndex};
        end

        if strcmp(selectedFolder, '<TS Folder>')

            setStatus( ...
                'Please select a TS Folder.', ...
                'warning');

            errordlg( ...
                'Please select a TS Folder.', ...
                'Plot Signal');

            return;

        end

        if strcmp(selectedSignal, '<Signal>')

            setStatus( ...
                'Please select a Signal.', ...
                'warning');

            errordlg( ...
                'Please select a Signal.', ...
                'Plot Signal');

            return;

        end

        plotInfo = struct();

        plotInfo.TsFolder = selectedFolder;
        plotInfo.Signal   = selectedSignal;
        plotInfo.Compare  = selectedCompare;

        setStatus( ...
            'Plotting selected signal...', ...
            'working');

        drawnow;

        try

            disp('Plot Signal');
            disp(plotInfo);

            setStatus( ...
                'Signal plotted successfully.', ...
                'success');

        catch ME

            setStatus( ...
                'Signal plotting failed.', ...
                'error');

            errordlg( ...
                ME.message, ...
                'Plot Signal');

        end

    end


    function generateReportCallback(~, ~)

        targetCoverageString = strtrim( ...
            get(handles.TargetCoverageEdit, 'String'));

        targetCoverage = str2double( ...
            targetCoverageString);

        if isnan(targetCoverage) || ...
                ~isfinite(targetCoverage)

            setStatus( ...
                'Target Coverage must be a numeric value.', ...
                'warning');

            errordlg( ...
                'Target Coverage must be a numeric value.', ...
                'Generate Report');

            return;

        end

        if targetCoverage < 0 || targetCoverage > 100

            setStatus( ...
                'Target Coverage must be between 0 and 100.', ...
                'warning');

            errordlg( ...
                'Target Coverage must be between 0 and 100.', ...
                'Generate Report');

            return;

        end

        coverageOptions = get( ...
            handles.CoverageTypeDropdown, ...
            'String');

        coverageIndex = get( ...
            handles.CoverageTypeDropdown, ...
            'Value');

        if ischar(coverageOptions)
            coverageType = coverageOptions;
        else
            coverageType = coverageOptions{coverageIndex};
        end

        reportInfo = struct();

        reportInfo.TargetCoverage = targetCoverage;
        reportInfo.CoverageType   = coverageType;

        setStatus( ...
            'Generating coverage report...', ...
            'working');

        drawnow;

        try

            disp('Generate Report');
            disp(reportInfo);

            setStatus( ...
                'Coverage report generated successfully.', ...
                'success');

        catch ME

            setStatus( ...
                'Coverage report generation failed.', ...
                'error');

            errordlg( ...
                ME.message, ...
                'Generate Report');

        end

    end


    function populateTsFolders()

        tsFolders = {};

        if isempty(tsFolders)

            set(handles.FolderDropdown, ...
                'String', {'<TS Folder>'}, ...
                'Value', 1);

        else

            folderList = [ ...
                {'<TS Folder>'}, ...
                tsFolders];

            set(handles.FolderDropdown, ...
                'String', folderList, ...
                'Value', 1);

        end

    end


    function setStatus(statusMessage, statusType)

        if nargin < 2
            statusType = 'ready';
        end

        hFigure = ancestor( ...
            handles.MainPanel, ...
            'figure');

        if isempty(hFigure) || ~ishandle(hFigure)
            return;
        end

        appData = guidata(hFigure);

        if isempty(appData) || ...
                ~isstruct(appData) || ...
                ~isfield(appData, 'StatusText') || ...
                ~isfield(appData, 'StatusIndicator')

            return;

        end

        switch lower(statusType)

            case 'working'
                indicatorColor = [0.125 0.350 0.620];

            case 'success'
                indicatorColor = [0.145 0.520 0.330];

            case 'warning'
                indicatorColor = [0.850 0.560 0.120];

            case 'error'
                indicatorColor = [0.720 0.220 0.220];

            otherwise
                indicatorColor = [0.145 0.520 0.330];

        end

        set(appData.StatusText, ...
            'String', statusMessage);

        set(appData.StatusIndicator, ...
            'ForegroundColor', indicatorColor);

        drawnow;

    end


    function buttonHandles = createRoundedButton( ...
            parentAxes, ...
            position, ...
            buttonText, ...
            backgroundColor, ...
            textColor, ...
            callbackFunction)

        buttonHandles = struct();

        buttonHandles.Background = rectangle( ...
            'Parent', parentAxes, ...
            'Position', position, ...
            'Curvature', [0.08 0.20], ...
            'FaceColor', backgroundColor, ...
            'EdgeColor', backgroundColor, ...
            'LineWidth', 1, ...
            'ButtonDownFcn', callbackFunction);

        textX = position(1) + position(3) / 2;
        textY = position(2) + position(4) / 2;

        buttonHandles.Text = text( ...
            textX, ...
            textY, ...
            buttonText, ...
            'Parent', parentAxes, ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', ...
            'FontName', 'Segoe UI', ...
            'FontSize', 10, ...
            'FontWeight', 'bold', ...
            'Color', textColor, ...
            'Interpreter', 'none', ...
            'ButtonDownFcn', callbackFunction);

    end

end
