function handles = view_TestCaseManagement(parentPanel)
% VIEW_TESTCASEMANAGEMENT Create the Test Case Management view.
%
% Input:
%   parentPanel - Parent uipanel supplied by MainApplication.
%
% Output:
%   handles     - Structure containing view graphics handles.

    C.Background      = [0.945 0.953 0.965];
    C.Card            = [1.000 1.000 1.000];
    C.CardBorder      = [0.855 0.875 0.905];
    C.TextPrimary     = [0.105 0.125 0.160];
    C.TextSecondary   = [0.420 0.455 0.510];
    C.InputBackground = [0.975 0.980 0.988];
    C.Primary         = [0.125 0.350 0.620];
    C.DarkButton      = [0.120 0.145 0.185];
    C.SecondaryButton = [0.900 0.920 0.945];
    C.Divider         = [0.900 0.915 0.935];
    C.White           = [1 1 1];

    handles.MainPanel = uipanel( ...
        'Parent', parentPanel, ...
        'Units', 'normalized', ...
        'Position', [0 0 1 1], ...
        'BackgroundColor', C.Background, ...
        'BorderType', 'none');

    handles.SourceAxes = axes( ...
        'Parent', handles.MainPanel, ...
        'Units', 'normalized', ...
        'Position', [0.045 0.620 0.91 0.330], ...
        'XLim', [0 1], ...
        'YLim', [0 1], ...
        'Visible', 'off', ...
        'Color', 'none');

    rectangle( ...
        'Parent', handles.SourceAxes, ...
        'Position', [0.005 0.01 0.99 0.98], ...
        'Curvature', [0.01 0.01], ...
        'FaceColor', C.Card, ...
        'EdgeColor', C.CardBorder, ...
        'LineWidth', 1);

    text( ...
        0.045, 0.865, ...
        'Test Case Source', ...
        'Parent', handles.SourceAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 13, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'Interpreter', 'none');

    text( ...
        0.045, 0.760, ...
        'Load and configure the test case source for simulation.', ...
        'Parent', handles.SourceAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 9.5, ...
        'Color', C.TextSecondary, ...
        'Interpreter', 'none');

    line( ...
        [0.045 0.955], ...
        [0.675 0.675], ...
        'Parent', handles.SourceAxes, ...
        'Color', C.Divider, ...
        'LineWidth', 1);

    text( ...
        0.045, 0.515, ...
        'Test Case File', ...
        'Parent', handles.SourceAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'VerticalAlignment', 'middle', ...
        'Interpreter', 'none');

    handles.TestCaseFileEdit = uicontrol( ...
        'Parent', handles.MainPanel, ...
        'Style', 'edit', ...
        'Units', 'normalized', ...
        'Position', [0.220 0.755 0.555 0.050], ...
        'String', '', ...
        'HorizontalAlignment', 'left', ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'ForegroundColor', C.TextPrimary, ...
        'BackgroundColor', C.InputBackground);

    handles.BrowseButton = createRoundedButton( ...
        handles.SourceAxes, ...
        [0.825 0.445 0.130 0.145], ...
        'Browse', ...
        C.SecondaryButton, ...
        C.TextPrimary, ...
        @(s,e)ut_callbacks('browseTestCaseFile', ancestor(handles.MainPanel, 'figure')));

    text( ...
        0.045, 0.245, ...
        'Sample Time', ...
        'Parent', handles.SourceAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'VerticalAlignment', 'middle', ...
        'Interpreter', 'none');

    handles.SampleTimeEdit = uicontrol( ...
        'Parent', handles.MainPanel, ...
        'Style', 'edit', ...
        'Units', 'normalized', ...
        'Position', [0.220 0.665 0.150 0.050], ...
        'String', '0.01', ...
        'HorizontalAlignment', 'left', ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'ForegroundColor', C.TextPrimary, ...
        'BackgroundColor', C.InputBackground);

    handles.LoadButton = createRoundedButton( ...
        handles.SourceAxes, ...
        [0.745 0.170 0.210 0.150], ...
        'Load Test Cases', ...
        C.Primary, ...
        C.White, ...
        @(s,e)ut_callbacks('loadTestCases', ancestor(handles.MainPanel, 'figure')));

    handles.ConfigAxes = axes( ...
        'Parent', handles.MainPanel, ...
        'Units', 'normalized', ...
        'Position', [0.045 0.055 0.91 0.545], ...
        'XLim', [0 1], ...
        'YLim', [0 1], ...
        'Visible', 'off', ...
        'Color', 'none');

    rectangle( ...
        'Parent', handles.ConfigAxes, ...
        'Position', [0.005 0.01 0.99 0.98], ...
        'Curvature', [0.01 0.01], ...
        'FaceColor', C.Card, ...
        'EdgeColor', C.CardBorder, ...
        'LineWidth', 1);

    text( ...
        0.040, 0.920, ...
        'Test Case Selection', ...
        'Parent', handles.ConfigAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 12, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'Interpreter', 'none');

    text( ...
        0.690, 0.920, ...
        'Execution Configuration', ...
        'Parent', handles.ConfigAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 12, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'Interpreter', 'none');

    line( ...
        [0.040 0.960], ...
        [0.840 0.840], ...
        'Parent', handles.ConfigAxes, ...
        'Color', C.Divider, ...
        'LineWidth', 1);

    line( ...
        [0.650 0.650], ...
        [0.080 0.760], ...
        'Parent', handles.ConfigAxes, ...
        'Color', C.Divider, ...
        'LineWidth', 1);

    text( ...
        0.040, 0.790, ...
        'Available Test Cases', ...
        'Parent', handles.ConfigAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'Interpreter', 'none');

    handles.AvailableList = uicontrol( ...
        'Parent', handles.MainPanel, ...
        'Style', 'listbox', ...
        'Units', 'normalized', ...
        'Position', [0.082 0.180 0.245 0.280], ...
        'String', {}, ...
        'Min', 0, ...
        'Max', 2, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'ForegroundColor', C.TextPrimary, ...
        'BackgroundColor', C.White, ...
        'Callback', @(s,e)ut_callbacks('availableDoubleClick', ancestor(handles.MainPanel, 'figure')));

    text( ...
        0.355, 0.790, ...
        'Selected Test Cases', ...
        'Parent', handles.ConfigAxes, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'FontWeight', 'bold', ...
        'Color', C.TextPrimary, ...
        'Interpreter', 'none');

    handles.SelectedList = uicontrol( ...
        'Parent', handles.MainPanel, ...
        'Style', 'listbox', ...
        'Units', 'normalized', ...
        'Position', [0.368 0.180 0.245 0.280], ...
        'String', {}, ...
        'Min', 0, ...
        'Max', 2, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'ForegroundColor', C.TextPrimary, ...
        'BackgroundColor', C.White);

    handles.SelectAllButton = createRoundedButton( ...
        handles.ConfigAxes, ...
        [0.040 0.075 0.270 0.115], ...
        'Select All', ...
        C.Primary, ...
        C.White, ...
        @(s,e)ut_callbacks('selectAllTestCases', ancestor(handles.MainPanel, 'figure')));

    handles.DeleteButton = createRoundedButton( ...
        handles.ConfigAxes, ...
        [0.355 0.075 0.270 0.115], ...
        'Delete Selected', ...
        C.DarkButton, ...
        C.White, ...
        @(s,e)ut_callbacks('deleteSelectedTestCases', ancestor(handles.MainPanel, 'figure')));

    handles.MILCheckbox = uicontrol( ...
        'Parent', handles.MainPanel, ...
        'Style', 'checkbox', ...
        'Units', 'normalized', ...
        'Position', [0.685 0.400 0.085 0.040], ...
        'String', 'MIL', ...
        'Value', 1, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'ForegroundColor', C.TextPrimary, ...
        'BackgroundColor', C.Card);

    handles.SILCheckbox = uicontrol( ...
        'Parent', handles.MainPanel, ...
        'Style', 'checkbox', ...
        'Units', 'normalized', ...
        'Position', [0.785 0.400 0.085 0.040], ...
        'String', 'SIL', ...
        'Value', 0, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'ForegroundColor', C.TextPrimary, ...
        'BackgroundColor', C.Card);

    handles.CoveragePopup = uicontrol( ...
        'Parent', handles.MainPanel, ...
        'Style', 'popupmenu', ...
        'Units', 'normalized', ...
        'Position', [0.670 0.275 0.245 0.045], ...
        'String', { ...
            'No Coverage', ...
            'Statement Coverage', ...
            'Decision Coverage'}, ...
        'Value', 1, ...
        'FontName', 'Segoe UI', ...
        'FontSize', 10, ...
        'ForegroundColor', C.TextPrimary, ...
        'BackgroundColor', C.White);

    handles.ExecuteButton = createRoundedButton( ...
        handles.ConfigAxes, ...
        [0.690 0.220 0.265 0.130], ...
        'Execute Simulation', ...
        C.Primary, ...
        C.White, ...
        @(s,e)ut_callbacks('executeSimulation', ancestor(handles.MainPanel, 'figure')));

    handles.GenerateCodeButton = createRoundedButton( ...
        handles.ConfigAxes, ...
        [0.690 0.075 0.265 0.110], ...
        'Generate Code', ...
        C.DarkButton, ...
        C.White, ...
        @(s,e)ut_callbacks('generateCode', ancestor(handles.MainPanel, 'figure')));


    function browseTestCaseFile(~, ~)

        [fileName, pathName] = uigetfile( ...
            { ...
                '*.xlsx;*.xls', ...
                'Excel Test Case Files (*.xlsx, *.xls)'; ...
                '*.*', ...
                'All Files (*.*)' ...
            }, ...
            'Select Test Case File');

        if isequal(fileName, 0)
            return;
        end

        testCaseFile = fullfile(pathName, fileName);

        set(handles.TestCaseFileEdit, ...
            'String', testCaseFile);

        setStatus( ...
            'Test case file selected.', ...
            'success');

    end


    function loadTestCasesCallback(~, ~)

        testCaseFile = strtrim( ...
            get(handles.TestCaseFileEdit, 'String'));

        sampleTime = str2double( ...
            get(handles.SampleTimeEdit, 'String'));

        if isempty(testCaseFile)

            setStatus( ...
                'Please select a Test Case File.', ...
                'warning');

            errordlg( ...
                'Please select a Test Case File.', ...
                'Test Case Management');

            return;

        end

        if exist(testCaseFile, 'file') ~= 2

            setStatus( ...
                'The selected Test Case File does not exist.', ...
                'error');

            errordlg( ...
                'The selected Test Case File does not exist.', ...
                'Test Case Management');

            return;

        end

        if isnan(sampleTime) || ...
                ~isfinite(sampleTime) || ...
                sampleTime <= 0

            setStatus( ...
                'Sample Time must be a positive numeric value.', ...
                'warning');

            errordlg( ...
                'Sample Time must be a positive numeric value.', ...
                'Test Case Management');

            return;

        end

        setStatus( ...
            'Loading test cases...', ...
            'working');

        drawnow;

        try

            disp('Load Test Cases');
            disp(testCaseFile);
            disp(sampleTime);

            testCases = {};

            set(handles.AvailableList, ...
                'String', testCases, ...
                'Value', []);

            set(handles.SelectedList, ...
                'String', {}, ...
                'Value', []);

            setStatus( ...
                'Test cases loaded successfully.', ...
                'success');

        catch ME

            setStatus( ...
                'Unable to load test cases.', ...
                'error');

            errordlg( ...
                ME.message, ...
                'Test Case Management');

        end

    end


    function selectAllCallback(~, ~)

        availableCases = get( ...
            handles.AvailableList, ...
            'String');

        if isempty(availableCases)

            setStatus( ...
                'No test cases are available.', ...
                'warning');

            return;

        end

        set(handles.SelectedList, ...
            'String', availableCases, ...
            'Value', []);

        setStatus( ...
            'All test cases selected.', ...
            'success');

    end


    function deleteSelectedCallback(~, ~)

        selectedCases = get( ...
            handles.SelectedList, ...
            'String');

        selectedIndices = get( ...
            handles.SelectedList, ...
            'Value');

        if isempty(selectedCases)

            setStatus( ...
                'No selected test cases are available.', ...
                'warning');

            return;

        end

        if isempty(selectedIndices)

            setStatus( ...
                'Select one or more test cases to delete.', ...
                'warning');

            return;

        end

        selectedIndices = selectedIndices( ...
            selectedIndices >= 1 & ...
            selectedIndices <= length(selectedCases));

        if isempty(selectedIndices)
            return;
        end

        selectedCases(selectedIndices) = [];

        set(handles.SelectedList, ...
            'String', selectedCases, ...
            'Value', []);

        setStatus( ...
            'Selected test cases removed.', ...
            'success');

    end


    function executeSimulationCallback(~, ~)

        selectedCases = get( ...
            handles.SelectedList, ...
            'String');

        if isempty(selectedCases)

            setStatus( ...
                'Select at least one Test Case.', ...
                'warning');

            errordlg( ...
                'Select at least one Test Case.', ...
                'Execute Simulation');

            return;

        end

        runMIL = logical( ...
            get(handles.MILCheckbox, 'Value'));

        runSIL = logical( ...
            get(handles.SILCheckbox, 'Value'));

        if ~runMIL && ~runSIL

            setStatus( ...
                'Select MIL, SIL, or both simulation modes.', ...
                'warning');

            errordlg( ...
                'Select MIL, SIL, or both simulation modes.', ...
                'Execute Simulation');

            return;

        end

        coverageOptions = get( ...
            handles.CoveragePopup, ...
            'String');

        coverageIndex = get( ...
            handles.CoveragePopup, ...
            'Value');

        if ischar(coverageOptions)
            selectedCoverage = coverageOptions;
        else
            selectedCoverage = ...
                coverageOptions{coverageIndex};
        end

        executionInfo = struct();

        executionInfo.TestCases = selectedCases;
        executionInfo.MIL       = runMIL;
        executionInfo.SIL       = runSIL;
        executionInfo.Coverage  = selectedCoverage;

        setStatus( ...
            'Executing simulation...', ...
            'working');

        drawnow;

        try

            disp('Execute Simulation');
            disp(executionInfo);

            setStatus( ...
                'Simulation completed successfully.', ...
                'success');

        catch ME

            setStatus( ...
                'Simulation execution failed.', ...
                'error');

            errordlg( ...
                ME.message, ...
                'Execute Simulation');

        end

    end


    function generateCodeCallback(~, ~)

        selectedCases = get( ...
            handles.SelectedList, ...
            'String');

        if isempty(selectedCases)

            setStatus( ...
                'Select at least one Test Case.', ...
                'warning');

            errordlg( ...
                'Select at least one Test Case.', ...
                'Generate Code');

            return;

        end

        setStatus( ...
            'Generating code...', ...
            'working');

        drawnow;

        try

            disp('Generate Code');
            disp(selectedCases);

            setStatus( ...
                'Code generated successfully.', ...
                'success');

        catch ME

            setStatus( ...
                'Code generation failed.', ...
                'error');

            errordlg( ...
                ME.message, ...
                'Generate Code');

        end

    end


    function setStatus(statusMessage, statusType)

        if nargin < 2
            statusType = 'ready';
        end

        hFigure = ancestor( ...
            handles.MainPanel, ...
            'figure');

        if isempty(hFigure) || ~ishandle(hFigure)
            return;
        end

        appData = guidata(hFigure);

        if isempty(appData) || ...
                ~isstruct(appData) || ...
                ~isfield(appData, 'StatusText') || ...
                ~isfield(appData, 'StatusIndicator')

            return;

        end

        switch lower(statusType)

            case 'working'
                indicatorColor = [0.125 0.350 0.620];

            case 'success'
                indicatorColor = [0.145 0.520 0.330];

            case 'warning'
                indicatorColor = [0.850 0.560 0.120];

            case 'error'
                indicatorColor = [0.720 0.220 0.220];

            otherwise
                indicatorColor = [0.145 0.520 0.330];

        end

        set(appData.StatusText, ...
            'String', statusMessage);

        set(appData.StatusIndicator, ...
            'ForegroundColor', indicatorColor);

        drawnow;

    end


    function buttonHandles = createRoundedButton( ...
            parentAxes, ...
            position, ...
            buttonText, ...
            backgroundColor, ...
            textColor, ...
            callbackFunction)

        buttonHandles = struct();

        buttonHandles.Background = rectangle( ...
            'Parent', parentAxes, ...
            'Position', position, ...
            'Curvature', [0.08 0.20], ...
            'FaceColor', backgroundColor, ...
            'EdgeColor', backgroundColor, ...
            'LineWidth', 1, ...
            'ButtonDownFcn', callbackFunction);

        textX = position(1) + position(3) / 2;
        textY = position(2) + position(4) / 2;

        buttonHandles.Text = text( ...
            textX, ...
            textY, ...
            buttonText, ...
            'Parent', parentAxes, ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', ...
            'FontName', 'Segoe UI', ...
            'FontSize', 10, ...
            'FontWeight', 'bold', ...
            'Color', textColor, ...
            'Interpreter', 'none', ...
            'ButtonDownFcn', callbackFunction);

    end

end
